### ISSUE TITLE
Stuck with getting bitmap from remote Video View

### ISSUE THREAD

**Issue by Vidoje** [twilio/video-quickstart-android#323] opened 2018-08-22 08:46 UTC
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

[Description of the issue]
Hello guys. I want to get bitmap from participant(remote) video view and later I would save that file.
Error which I get as soon as I call method takeSnapshot from SnapshotVideo renderer class is this
AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.appthe30.the30, PID: 3443
                                                                  java.lang.RuntimeException: glCreateShader() failed. GLES20 er..

I checked here all possible solutions but either I'm doing something wrong or don't understand how to resolve this. Could you please help? Thanks in advance

### Steps to Reproduce
1. For that purpose I'm using SnapshotVideoRenderer which extends VideoView.
2. Here I add snapshotVideoRenderer to participant video track

 snapshotVideoRenderer = new SnapshotVideoRenderer(this, null);
        videoTrack.addRenderer(snapshotVideoRenderer);

2. hen I call takeSnapshot method from SnapshotVideoRenderer I get this error

08-22 10:36:28.996 3443-3443/com.appthe30.the30 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.appthe30.the30, PID: 3443
                                                                  java.lang.RuntimeException: glCreateShader() failed. GLES20 error: 0
                                                                      at org.webrtc.GlShader.compileShader(GlShader.java:24)
                                                                      at org.webrtc.GlShader.<init>(GlShader.java:42)
                                                                      at org.webrtc.YuvConverter.<init>(YuvConverter.java:118)
                                                                      at com.appthe30.the30.util.SnapshotVideoRenderer.captureBitmapFromTexture(SnapshotVideoRenderer.java:106)
                                                                      at com.appthe30.the30.util.SnapshotVideoRenderer.access$000(SnapshotVideoRenderer.java:31)
                                                                      at com.appthe30.the30.util.SnapshotVideoRenderer$1.run(SnapshotVideoRenderer.java:69)
                                                                      at android.os.Handler.handleCallback(Handler.java:789)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                      at android.os.Looper.loop(Looper.java:164)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6944)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
08-22 10:36:28.996 3443-3443/com.appthe30.the30 E/UncaughtException: java.lang.RuntimeException: glCreateShader() failed. GLES20 error: 0
                                                                         at org.webrtc.GlShader.compileShader(GlShader.java:24)
                                                                         at org.webrtc.GlShader.<init>(GlShader.java:42)
                                                                         at org.webrtc.YuvConverter.<init>(YuvConverter.java:118)
                                                                         at com.appthe30.the30.util.SnapshotVideoRenderer.captureBitmapFromTexture(SnapshotVideoRenderer.java:106)
                                                                         at com.appthe30.the30.util.SnapshotVideoRenderer.access$000(SnapshotVideoRenderer.java:31)
                                                                         at com.appthe30.the30.util.SnapshotVideoRenderer$1.run(SnapshotVideoRenderer.java:69)
                                                                         at android.os.Handler.handleCallback(Handler.java:789)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                         at android.os.Looper.loop(Looper.java:164)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6944)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

#### Code

```java
// Code that help reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces how Often

[What percentage of the time does it reproduce?]

#### Logs

```
// Log output when issue occurs
```

### Versions

All relevant version information for issue.

#### Video Android SDK

[eg. 1.0.2]

#### Android API

[eg. 18]

#### Android Device

[eg. Samsung S7]

**Comment by aaalaniz** [comment] 2018-09-05 14:36
Hey @Vidoje 

This issue is a duplicate of #213. Please post your questions or findings there.

Thanks!

**Closed by aaalaniz** 2018-09-05 14:36 UTC
Labels: bug

**Comment by aaalaniz** [comment] 2018-09-05 15:20
Duplicate of #213
