### ISSUE TITLE
Crash when using MediaRecorder with live audio and video tracks

### ISSUE THREAD

**Issue by spalmertwilio** [twilio/video-quickstart-android#351] opened 2018-10-27 13:13 UTC
### Description

We are using Twilio "ScreenCapturer" to capture the screen and show to other room users. It is working fine. 
But here I am also capturing video(With Audio) using my device camera. Here video cannot be recorded as Twilio holding the mic of this device. and that conflicts because the audio input resource is not sharable. 

We want to be sending the audio track to Twilio & also record video with audio with at the same time.

We are unable to do so. Our use case is to stream, have chat with the other room participants & record locally the video at the same time. 

We received a reply from Twilio Support in case 1521974:

> It's currently not possible to send your audioTrack to Twilio as a participant and also record it locally at the same time. 

Our questions:

- Did we receive the correct response?
- If we can use ttps://developer.android.com/guide/topics/media/mediarecorder do you have some guidance?
- Can Twilio accept Audio buffer(Using AudioRecorder) for local audio track instead of accruing device mic?

#### Code

recorder = new MediaRecorder(); 
recorder.setCamera(mCamera); 
recorder.setVideoSource(MediaRecorder.VideoSource.DEFAULT); 
recorder.setAudioSource(MediaRecorder.AudioSource.MIC); 
recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4); 
recorder.setVideoEncodingBitRate(bitRate * 1000000); 
recorder.setVideoSize(screenSize.get(videoResolutionIndex).getWidth(), 
screenSize.get(videoResolutionIndex).getHeight()); 
recorder.setVideoEncoder(MediaRecorder.VideoEncoder.H264); 
recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC); 
recorder.setOutputFile(videoPath); 
recorder.setOrientationHint(currentViewOrientation); 
recorder.prepare(); 
recorder.start();

#### Expected Behavior

Record locally while being an active Participant of the Video room who is sharing device resources.

#### Actual Behavior

In my application, I am using "Twilio ScreenCapturer" as a video track to Twilio Video. And in the application, I am using my device camera to record video with audio using MediaRecorder API. But when I start recording the below error is occurring.

E/AndroidRuntime: FATAL EXCEPTION: main 
java.lang.IllegalStateException 
at android.media.MediaRecorder.start(Native Method) 
at com.uipl.cleardoc.VideoActivity.initRecorder(VideoActivity.java:7291) 
at com.uipl.cleardoc.VideoActivity.access$14200(VideoActivity.java:194) 
at com.uipl.cleardoc.VideoActivity$102.onFinish(VideoActivity.java:7236) 
at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:163) 
at android.app.ActivityThread.main(ActivityThread.java:6221) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

#### Video Android SDK

Twilio Version : com.twilio:video-android:2.2.0

##### Android API

26

##### Example:

Room Sid : RMddcdcd7a49e30458d47bdba232fdca80

**Comment by aaalaniz** [comment] 2018-10-30 16:05
> Can Twilio accept Audio buffer(Using AudioRecorder) for local audio track instead of accruing device mic?

The answer to this question is no and the feature is captured in #353

**Comment by zackm0571** [comment] 2019-02-07 20:57
Closing as a duplicate of #353

**Closed by zackm0571** 2019-02-07 20:57 UTC
Labels: bug
