### ISSUE TITLE
VideoView.renderFrame frame.yuvPlanes is null

### ISSUE THREAD

**Issue by namhvcntt** [twilio/video-quickstart-android#138] opened 2017-07-11 02:55 UTC
CustomVideoView
`public class CustomVideoView extends VideoView {
    public CustomVideoView(Context context) {
        super(context);
    }

    public CustomVideoView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public void renderFrame(I420Frame frame) {
        Log.e(VIEW_LOG_TAG, "Frame: " + (frame == null));
        ByteBuffer[] yuvPlanes = frame.yuvPlanes;
        if (null != yuvPlanes) {
            ByteBuffer yData = yuvPlanes[0];
            Log.e(VIEW_LOG_TAG, "Frame: Y: " + Arrays.toString(yData.array()));
            ByteBuffer uData = yuvPlanes[1];
            ByteBuffer vData = yuvPlanes[1];
        }
        super.renderFrame(frame);
    }
}`

#### Video Android SDK

[eg. 1.1.0]

#### Android Device

[eg. Nexus 5]

**Comment by aaalaniz** [comment] 2017-07-11 20:51
Hey @namhvcntt 

`I420Frame#yuvPlanes` can be null in the event that the frame is decoded from a texture. See the comment in our [custom renderer example](https://github.com/twilio/video-quickstart-android/blob/master/exampleCustomVideoRenderer/src/main/java/com/twilio/video/examples/customrenderer/SnapshotVideoRenderer.java#L47). We currently decode a Participant's video to a texture and as a result, the in memory buffer is not necessary. If you would like to extract the frame from the texture I recommend referencing our [custom renderer example](https://github.com/twilio/video-quickstart-android/blob/master/exampleCustomVideoRenderer/src/main/java/com/twilio/video/examples/customrenderer/SnapshotVideoRenderer.java#L72).

**Comment by namhv** [comment] 2017-07-12 05:00
How can I change Video bright?

**Comment by aaalaniz** [comment] 2017-07-13 14:40
Closing because the issue reported is expected behavior in some cases and we have [an example](https://github.com/twilio/video-quickstart-android/blob/master/exampleCustomVideoRenderer/src/main/java/com/twilio/video/examples/customrenderer/SnapshotVideoRenderer.java#L72) to demonstrate how to work with in-memory frames and frames represented as textures.

**Closed by aaalaniz** 2017-07-13 14:40 UTC
Labels: question
