### ISSUE TITLE
Microphone audio inaudible after enabling their speakerphone on an Android 7.0 device

### ISSUE THREAD

**Issue by idelgado** [twilio/video-quickstart-android#63] opened 2017-02-23 16:06 UTC
A customer reported this problem via Zendesk using a Sony Xperia Z5 with Android 7.0:

I have encountered a problem while using the programmable video service on Android 7.0 (the problem seems to vanish on earlier versions).

While using the Android Video Quickstart example code, I added a button to activate the speaker of the phone. This was done by replacing the the code in the muteClickListener() onClick() method by the following lines of code in Java:

```
if (audioManager.isSpeakerphoneOn()) { 
audioManager.setSpeakerphoneOn(false); 
} else { 
audioManager.setSpeakerphoneOn(true); 
} 
Toast.makeText(getApplicationContext(), "Now speaker status is: " + audioManager.isSpeakerphoneOn(), Toast.LENGTH_LONG).show(); 
```

What this code does is that when I click on mute (the FloatingActionButton in the activity in the provided example code), it toggles between turning on and off the speaker.

The problem is that when launching the videoconference between an Android 6.0.1 and an Android 7.0, if I switch on the speaker on the Android 7.0, the sound does come out from the speaker as expected, however the person on the Android 6.0.1 can no longer hear me properly (the volume on his end decreases greatly, and the voice is pretty much inaudible even at max volume). It seems as if when turning on the speaker on Android 7.0 the microphone sensitivity is decreased (maybe to prevent the sound from the speaker from going back into the mic and causing echo on the other side?).

As a reference, I have run the same experiment between an Android 6.0.1 and an Android 4.4.2, and in this case the problem does not occur, switching on/off the speakers works as expected, so it does seem like this is related to the newer Android 7.0.

However, when using Whatsapp audio/video calls the speaker works fine, so there must be a way to fix this. Maybe I need to do something special on Android 7.0 to make it work?

**Comment by aaalaniz** [comment] 2017-03-03 23:16
I am unable to reproduce this issue with the following 7.0 devices:

- Samsung Edge S7 - 7.0.0
- Nexus 9 - 7.1.1
- Nexus 6 - 7.0.0

I have been using a Samsung Galaxy S5 as my 6.0.1 device. 

I would like to investigate the issue with the actual Sony device. I will put in a request to get this sent to me. 

In the mean time, it might be worth trying to tweek the `LocalAudioTrack` via `AudioOptions` as a temporary workaround. I recommend disabling echo cancellation, auto gain control, and noise suppression to see if it has any affect on the audio played on the 6.0.1 device. Below is a snippet for how to add an audio track with options.

```
// Create local media 
LocalMedia localMedia = LocalMedia.create(context);

// Create audio options
AudioOptions audioOptions = new AudioOptions.Builder()
    .echoCancellation(false)
    .autoGainControl(false)
    .noiseSuppression(false)
    .build();

// Add audio track
LocalAudioTrack localAudioTrack = localMedia.addAudioTrack(true, audioOptions);
```

**Comment by dreamerns** [comment] 2017-03-14 21:34
Unfortunately, I wasn't able to reproduce it with Sony Xperia Z5 (E6603) with Android 7.0 either.

**Comment by aaalaniz** [comment] 2017-03-15 01:38
Closing this issue because we are having trouble reproducing with the Sony Xperia Z5. Feel free to reopen the issue if there is anything new to report.

**Closed by aaalaniz** 2017-03-15 01:38 UTC
Labels: bug
