### ISSUE TITLE
Streaming stops when slide animation is done

### ISSUE THREAD

**Issue by keshav1139** [twilio/video-quickstart-android#225] opened 2018-01-11 13:38 UTC
### Description

Streaming stops when slide animation is done 

### Steps to Reproduce

1. Start video
2. perform translation x animation

#### Code

```java
// Code that help reproduce the issue
 // Load the animation like this
  Animation animSlide;
 if (sessionParticipantsAdapter.getItemCount() == 1) {
   animSlide = android.view.animation.AnimationUtils.loadAnimation(getApplicationContext(),
 R.anim.right_slide);
} else {
 animSlide = android.view.animation.AnimationUtils.loadAnimation(getApplicationContext(),
   R.anim.right_slide_for_more_than_one_participant);
 }
// Start the animation like this
miniLayout.startAnimation(animSlide);
findViewById(R.id.iv_add_friends).setVisibility(View.GONE);
 miniLayout.setPadding(dpToPx(40), 0, 0, 0);
```
miniLayout is a frame layout and it contains a recycler view, I am streaming in the first item of recycler view and then will start animation slide

My Xml File :-  R.anim.right_slide_for_more_than_one_participant:

```
<?xml version="1.0" encoding="utf-8"?>
<set
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:interpolator="@android:anim/linear_interpolator"
    android:fillAfter="false">

    <translate
        android:fromXDelta="0%p"
        android:toXDelta="55%p"
        android:duration="500" />
</set>
```

#### Expected Behavior

Silde animation should happen and streaming should not stop

#### Actual Behavior

Slide animation happens but streaming also stops

#### Reproduces how Often

100%

#### Logs

```
// Log output when issue occurs
```

### Versions

Happens on all Android devices

#### Video Android SDK

Version 1.3.6
#### Android API

All API levels

#### Android Device
Happens on all Android Devices

**Comment by aaalaniz** [comment] 2018-01-11 16:41
Hey @keshav1139 

I will work on reproducing this issue locally. However, the issue may be caused by the `VideoView` being an extension of `SurfaceView`. Can you try using this gist I put together that allows rendering with a `TextureView` instead. Just copy the two files to your project and use the `VideoTextureView` like you are using the `VideoView` today. We will add an official `VideoTextureView` to the SDK this year. Thanks!

[Rendering with a TextureView](https://gist.github.com/aaalaniz/bfbc4891c98ef3b23558ff2260cbcc8e)

**Comment by keshav1139** [comment] 2018-01-11 18:07
Hey @aaalaniz  I used those files and changed ``` VideoView``` to ```VideoTextureView``` But I am getting this exception:
```
Caused by: java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable at android.view.TextureView.setBackgroundDrawable(TextureView.java:316)
```

Please let me know how can I move ahead..

**Comment by aaalaniz** [comment] 2018-01-11 18:10
Hey @keshav1139 

Are you setting a background drawable on the `VideoTextureView`?

**Comment by keshav1139** [comment] 2018-01-11 18:14
Hey @aaalaniz 

No. I am not.

**Comment by aaalaniz** [comment] 2018-01-11 18:17
Thanks for trying out the `VideoTextureView`. Let me investigate more and i'll get back to you.

Thanks @keshav1139

**Comment by keshav1139** [comment] 2018-01-11 18:22
Ok Sure. @aaalaniz

**Comment by aaalaniz** [comment] 2018-01-11 23:14
Hey @keshav1139 

I tested this out in the quickstart (see attached video) and I am not able to reproduce the problem. 

[Animation on RemoteParticipant video with `VideoView`](https://drive.google.com/file/d/1RpyQA_SgBnUIbIUPZ3yPIMDA2gRlCnI2/view?usp=sharing)

You mentioned using a RecyclerView. I have a reference Gist for using a RecyclerView with VideoView. Can you verify that you are handling the VideoView in a similar way?

[VideoView with RecyclerView](https://gist.github.com/aaalaniz/b779b12d2887c32576ffa4d5828b88c1)

If you still have problems can you try to reproduce the issue in the quickstart? Thanks!

**Comment by keshav1139** [comment] 2018-01-12 12:38
I did not see that issue today @aaalaniz .  I will get back to you further on this later.

**Comment by aaalaniz** [comment] 2018-02-22 15:40
Hey @keshav1139 

I'm closing this issue. Please reopen if you have any issues with animating a video view.

Thanks!

**Closed by aaalaniz** 2018-02-22 15:40 UTC
Labels: bug
