### ISSUE TITLE
Crashes happening while in session. Fatal signal 11(SIGSEGV)

### ISSUE THREAD

**Issue by VanKhulup** [twilio/video-quickstart-android#611] opened 2021-01-15 14:18 UTC
Hello! Recently I've noticed few crashes in the production version of the app, which occurred in the JNI layer, so I'm not sure how to tackle them. I'm not 100% sure if this is a Twilio-related issue, but these issues started popping up with the first release, which contained Twilio support (previously app used a different WebRTC provider).
The steps are unclear, seems like the app gets SIGSEGV error just at random moment during the session. 
Logs right before the crash looks as this: 
```
2021-01-15 14:53:06.016 3765-3765 V/VideoTextureView: onSurfaceTextureUpdated
2021-01-15 14:53:06.070 3765-3765 V/VideoTextureView: onSurfaceTextureUpdated
2021-01-15 14:53:06.093 3765-5869 V/Twilio: [Core](510018974960): static void twilio::insights::InsightsPublisher::processStatsRequest(std::weak_ptr<InsightsPublisher>)
2021-01-15 14:53:06.094 3765-5869 V/Twilio: [Core](510018974960): void twilio::signaling::PeerConnectionSignaling::getStats(webrtc::StatsObserver *)
2021-01-15 14:53:06.094 3765-5869 V/Twilio: [Core](510018974960): Posting kGetStats to signaling thread.
2021-01-15 14:53:06.094 3765-5858 V/Twilio: [Core](MediaFactoryImpl::signaling 0x0x76dcc3c4a0): virtual void twilio::signaling::PeerConnectionSignaling::OnMessage(rtc::Message *)
2021-01-15 14:53:06.094 3765-5858 V/Twilio: [Core](MediaFactoryImpl::signaling 0x0x76dcc3c4a0): void twilio::signaling::PeerConnectionSignaling::doGetStats(twilio::signaling::PeerConnectionSignaling::GetStatsData *const)
2021-01-15 14:53:06.094 3765-5858 V/Twilio: [Core](MediaFactoryImpl::signaling 0x0x76dcc3c4a0): doGetStats: Calling GetStats()
2021-01-15 14:53:06.102 3765-5858 V/Twilio: [Core](MediaFactoryImpl::signaling 0x0x76dcc3c4a0): doGetStats: GetStats() returned.
2021-01-15 14:53:06.102 3765-5858 V/Twilio: [Core](MediaFactoryImpl::signaling 0x0x76dcc3c4a0): virtual void twilio::stats::(anonymous namespace)::PeerConnectionStatsObserver::OnComplete(const webrtc::StatsReports &)
2021-01-15 14:53:06.103 3765-5858 V/Twilio: [Core](MediaFactoryImpl::signaling 0x0x76dcc3c4a0): Posting worker queue task to send stats to observer
2021-01-15 14:53:06.103 3765-5869 V/Twilio: [Core](510018974960): Calling observer::onStats()
2021-01-15 14:53:06.103 3765-5869 V/Twilio: [Core](510018974960): virtual void twilio::insights::InsightsPublisher::onStats(const std::vector<media::StatsReport> &)
2021-01-15 14:53:06.103 3765-5869 V/Twilio: [Core](510018974960): void twilio::insights::InsightsPublisher::sendMessage(const twilio::insights::InsightsMessageBase &)
2021-01-15 14:53:06.109 3765-5869 V/Twilio: [Core](510018974960): Sending message to Insights server: {"group":"quality","name":"stats-report","payload":{"audioTrackStats":[{"audioLevel":0,"bytesReceived":0,"codec":"","jitter":0,"packetsLost":0,"packetsReceived":0,"ssrc":"750665962","timestamp":1610715186094.0,"trackId":"dd6bdf78-f4a0-4ba1-a82c-d18e58e0ea3a","trackSid":"MTa6a050080eefcb6bf0c7549cd992476e"}],"localAudioTrackStats":[{"audioLevel":6,"bytesSent":47807,"codec":"opus","jitter":2,"packetsLost":0,"packetsSent":1297,"roundTripTime":202,"ssrc":"4062247014","timestamp":1610715186094.0,"trackId":"D392BCdB511B73F76FDC9EAaBeaEdfeA","trackSid":"MTbcfdc3b15a12f02b92ae37d553dac225"}],"localVideoTrackStats":[{"bytesSent":43384428,"captureDimensions":{"height":1920,"width":1080},"captureFrameRate":0,"codec":"H264","dimensions":{"height":960,"width":528},"frameRate":0,"packetsLost":0,"packetsSent":38322,"roundTripTime":202,"ssrc":"25594747","timestamp":1610715186094.0,"trackId":"36AF34e9DFfCCaeFe289aDa18AFda824","trackSid":"MT94b3a63f2c864f00b8357d8f18d8
2021-01-15 14:53:06.110 3765-5869 V/Twilio: [Core](510018974960): virtual bool twilio::insights::InsightsSocket::send(const std::vector<unsigned char> &)
2021-01-15 14:53:06.110 3765-5869 V/Twilio: [Core](510018974960): std::future<std::size_t> twilio::net::WebSocket::Session::write(const asio::const_buffer &)
2021-01-15 14:53:06.110 3765-5869 V/Twilio: [Core](510018974960): void twilio::net::WebSocket::Implementation::write(const asio::const_buffer &, std::promise<std::size_t> &&)
2021-01-15 14:53:06.115 3765-5869 V/Twilio: [Core](510018974960): void twilio::insights::InsightsPublisher::sendMessage(const twilio::insights::InsightsMessageBase &)
2021-01-15 14:53:06.119 3765-5869 V/Twilio: [Core](510018974960): Sending message to Insights server: {"group":"quality","name":"active-ice-candidate-pair","payload":{"availableIncomingBitrate":1648240.0,"availableOutgoingBitrate":1589440.0,"bytesReceived":24449818,"bytesSent":44646371,"consentRequestsSent":0,"currentRoundTripTime":201.0,"lastPacketReceivedTimestamp":0.0,"lastPacketSentTimestamp":0.0,"localCandidate":{"candidateType":"srflx","deleted":false,"ip":"176.36.172.41","port":43603,"priority":1686052607,"protocol":"udp","relayProtocol":"udp","url":""},"nominated":false,"peerConnectionId":"FcE6DaafbbFAF7CAFBa9D2CFA97e0a8E","priority":0,"readable":false,"remoteCandidate":{"candidateType":"host","ip":"44.234.69.85","port":18259,"priority":2013266430,"protocol":"udp","url":""},"requestsReceived":0,"requestsSent":0,"responsesReceived":0,"responsesSent":0,"retransmissionsReceived":0,"retransmissionsSent":0,"state":"succeeded","totalRoundTripTime":0.0,"transportId":"Channel-audio-1","writable":true},"session":"0772626f-6c8a-4ec6-8a8e-4a851d10c962","
2021-01-15 14:53:06.119 3765-5869 V/Twilio: [Core](510018974960): virtual bool twilio::insights::InsightsSocket::send(const std::vector<unsigned char> &)
2021-01-15 14:53:06.119 3765-5869 V/Twilio: [Core](510018974960): std::future<std::size_t> twilio::net::WebSocket::Session::write(const asio::const_buffer &)
2021-01-15 14:53:06.119 3765-5869 V/Twilio: [Core](510018974960): void twilio::net::WebSocket::Implementation::write(const asio::const_buffer &, std::promise<std::size_t> &&)
2021-01-15 14:53:06.119 3765-5869 V/Twilio: [Core](510018974960): observer::onStats() returned
2021-01-15 14:53:06.120 3765-6077 V/Twilio: [Core](509974934768): void twilio::net::WebSocket::Implementation::on_write(const beast::error_code &, const std::size_t)
2021-01-15 14:53:06.120 3765-6077 V/Twilio: [Core](509974934768): void twilio::net::WebSocket::Implementation::on_write(const beast::error_code &, const std::size_t)
2021-01-15 14:53:06.141 3765-3765 V/VideoTextureView: onSurfaceTextureUpdated
2021-01-15 14:53:06.169 3765-6150 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3 in tid 6150 (EncoderQueue - ), pid 3765 (company.video)
2021-01-15 14:53:06.236 3765-6077 V/Twilio: [Core](509974934768): void twilio::net::WebSocket::Implementation::on_read(const beast::error_code &, const std::size_t)
2021-01-15 14:53:06.237 3765-6077 V/Twilio: [Core](509974934768): onMessage
2021-01-15 14:53:06.239 3765-5869 V/Twilio: [Core](510018974960): virtual void twilio::insights::InsightsPublisher::handleMessage(const std::string &)
2021-01-15 14:53:06.239 3765-5869 V/Twilio: [Core](510018974960): Received ok message from Insights server: {"type":"ok","message":""}
2021-01-15 14:53:06.252 3765-3765 V/VideoTextureView: onSurfaceTextureUpdated
2021-01-15 14:53:06.267 3765-6227 I/Adreno: Invalid colorspace 0
2021-01-15 14:53:06.285 3765-3765 V/VideoTextureView: onSurfaceTextureUpdated
2021-01-15 14:53:06.329 3765-6219 I/tvi.webrtc.Logging: EglRenderer: Duration: 4005 ms. Frames received: 20. Dropped: 0. Rendered: 20. Render fps: 5.0. Average render time: 3534 us. Average swapBuffer time: 1912 us.
2021-01-15 14:53:10.825 3765-6223 W/AudioTrack: releaseBuffer() track 0x76ba91c800 disabled due to previous underrun, restarting
2021-01-15 14:53:10.826 3765-6077 V/Twilio: [Core](509974934768): void twilio::net::WebSocket::Implementation::on_read(const beast::error_code &, const std::size_t)
2021-01-15 14:53:10.826 3765-6077 V/Twilio: [Core](509974934768): onMessage
```

The crash reporting system gets the following: 
``` 
SIGSEGV Segmentation violation (invalid memory reference) 
    /data/app/my.company.video-dTjoo177yzzsxcWu_5mM9A==/base.apk!/lib/arm64-v8a/libtwilio_video_android_so.so:6451488 0x76bb768120
```

The device is Nexus 5, running Android 8.1.0, Twilio SDK version is 6.0.0. 
The production version is shipped via App Bundles (if this could cause the problem). 

Other production issues are various:
``` 
SIGABRT Abort program 
    /system/lib/libc.so:305824 tgkill
    /system/lib/libc.so:107575 abort
```

```
SIGSEGV Segmentation violation (invalid memory reference) 
    /system/lib/libandroid_runtime.so:881256 JNICameraContext::copyAndPost(_JNIEnv*, android::sp<android::IMemory> const&, int)
    /system/lib/libandroid_runtime.so:881687 JNICameraContext::postData(int, android::sp<android::IMemory> const&, camera_frame_metadata*)
    /system/lib/libcamera_client.so:132641 android::Camera::dataCallback(int, android::sp<android::IMemory> const&, camera_frame_metadata*)
    /system/lib/libcamera_client.so:156845 android::hardware::BnCameraClient::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)
    /system/lib/libbinder.so:236121 android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)
    /system/lib/libbinder.so:268117 android::IPCThreadState::executeCommand(int)
    /system/lib/libbinder.so:267217 android::IPCThreadState::getAndExecuteCommand()
    /system/lib/libbinder.so:268543 android::IPCThreadState::joinThreadPool(bool)
    /system/lib/libbinder.so:360429 0xadde4fed
    /system/lib/libutils.so:54379 android::Thread::_threadLoop(void*)
    /system/lib/libandroid_runtime.so:430027 android::AndroidRuntime::javaThreadShell(void*)
    /system/lib/libc.so:294345 0xabdc7dc9
    /system/lib/libc.so:110775 0xabd9b0b7
```

```
SIGABRT Abort program 
    /system/lib/libc.so:118546 abort
    /system/lib/libc.so:119751 __assert2
    /data/app/my.company.video-qDH_AnzarGVUDy77QcxXjw==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libtwilio_video_android_so.so:6163101 0x92353a9d
    /data/app/my.company.video-qDH_AnzarGVUDy77QcxXjw==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libtwilio_video_android_so.so:6163357 0x92353b9d
    /data/app/my.company.video.qDH_AnzarGVUDy77QcxXjw==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libtwilio_video_android_so.so:6156271 0x92351fef
    /data/app/my.company.video-qDH_AnzarGVUDy77QcxXjw==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libtwilio_video_android_so.so:6154655 __cxa_get_exception_ptr
    /data/app/my.company.video-qDH_AnzarGVUDy77QcxXjw==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libtwilio_video_android_so.so:6154599 __cxa_throw
    /data/app/my.company.video-qDH_AnzarGVUDy77QcxXjw==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libtwilio_video_android_so.so:6106913 operator new(unsigned int)
```

The steps are commonly following - users join the video session, stay in it for 1-2-5 minutes, and they crash. Another thing, which I might call a suspect for this I'm still forced to use old WebRTC provider during the rollout period, so there are 2 dependencies in the app, who has WebRTC lib as their dependency (potential conflict of versions?).

I would appreciate any hints for solving or further investigating the issue.

**Comment by Alton09** [comment] 2021-01-19 16:56
Hi @VanKhulup . Thank you for reaching out. Can you please provide a room SID to help us troubleshoot the issue further? This can be gathered by searching the logs for "room sid". Also, can you further elaborate on using two WebRTC versions? Does this mean you are using another SDK/lib that utilizes WebRTC? The crash may be coming from the other dependency. If you could also provide the other WebRTC dependency that would be helpful. Thanks!

**Comment by VanKhulup** [comment] 2021-01-19 17:30
Hi @Alton09 !  SIDs: 
```
RMd910b8c03117c20b8a664d89e3cf4330
RM9705a9b036a8968d823c74d853793d5a
RM47eced1cf7f564951c9adb66716f6859
RM33515eb6184b7f037fcb5f557d2d8983
RM594c1a37cd322f022dbd01d733a9e575
RMb100138b55c9aa08d995f2280b0a6e8e
RMb22322843b9253df77268e7b5c159c88
RMb22322843b9253df77268e7b5c159c88
```

Regarding other WebRTC library - our app was previously using another library for video sessions, which is also based on WebRTC implementation. So now, during the migration phase, our app has both Twilio and this other library as a dependency. In runtime, our API determines, which provider hosts a specific room(based on our internal roomID), and based on that I'm initializing either Twilio-related viewModels, or another viewModels. I'm assuming that this might is related to Twilio SDK because SIDs are from Twilio, which means the other library's SDK is not initialized in runtime.

**Comment by Alton09** [comment] 2021-01-19 17:55
Thanks for the additional information @VanKhulup. I'll dig into this further when I have some time this week. Are you able to reproduce this issue locally on a test device? If so, in the meantime I'd suggest attempting to only package the app bundle with one of the libraries at a time to find the root cause of the crash.

**Comment by Alton09** [comment] 2021-01-26 19:34
@VanKhulup any luck attempting the above to determine which WebRTC dependency is the culprit? Thanks.

**Comment by Alton09** [comment] 2021-02-09 16:35
Closing this one for now. Please feel free to reopen if the issue persists. Thanks!

**Closed by Alton09** 2021-02-09 16:35 UTC
Labels: help wanted
