### ISSUE TITLE
Android X connectivity is not stable

### ISSUE THREAD

**Issue by amirocpc** [twilio/video-quickstart-android#547] opened 2020-07-16 17:52 UTC
Ok so we have updated to Android X and here is the code: https://github.com/mukeshocpc/TwillioSample
We have tested this more than 50 times but it's not stable. Call usually drops in less than 1 minute, sometimes it doesn't disconnect.
Can you please check this and tell us how to fix this?

Notes: We have super high speed internet connections. Issue happened in Android 8 and 9 as well. Attached log might help. We don't have this issue in iOS.

[calltwillo.log](https://github.com/twilio/video-quickstart-android/files/4933280/calltwillo.log)

**Comment by amirocpc** [comment] 2020-07-20 18:36
@aaalaniz have you had a chance to check on this?

**Comment by aaalaniz** [comment] 2020-07-24 18:39
Hey @amirocpc 

Thank you for the sample project. I do not know of any compatibility issues with respect to connectivity in apps that use AndroidX. I will investigate your logs and project and see what I find.

Thanks!

**Comment by aaalaniz** [comment] 2020-07-24 18:47
Hey @amirocpc 

The log you provided does not indicate any connectivity problems. I did look at your example project and noticed the following code snippet.

```
        override fun onVideoTrackUnsubscribed(
            remoteParticipant: RemoteParticipant,
            remoteVideoTrackPublication: RemoteVideoTrackPublication,
            remoteVideoTrack: RemoteVideoTrack
        ) {
            Log.i(
                TAG, "onVideoTrackUnsubscribed: " +
                        "[RemoteParticipant: identity=${remoteParticipant.identity}], " +
                        "[RemoteVideoTrack: enabled=${remoteVideoTrack.isEnabled}, " +
                        "name=${remoteVideoTrack.name}]"
            )
            videoStatusTextView.text = "onVideoTrackUnsubscribed"
            removeParticipantVideo(remoteVideoTrack)
            showToast("Call Disconnected")
            onBackPressed()
        }
```

It looks like when a video track is unsubscribed, the app will invoke `onBackPressed`. I'm not sure this is intended behavior or not, but it would probably result in some unexpected disconnections. I recommend referring to either our [Kotlin quickstart](https://github.com/twilio/video-quickstart-android/tree/master/quickstartKotlin) or the [Video Android app](https://github.com/twilio/twilio-video-app-android) as you are building out your solutions. I will close this ticket for now. 

Thanks!

**Closed by aaalaniz** 2020-07-24 18:47 UTC
Labels: bug

**Comment by amirocpc** [comment] 2020-07-28 18:28
Hello, we tried what you suggested but the issue is still there. Attached is a more detailed log for both caller and receiver:

Here is the observation for call and receive in android 8 and 9:
User A is able to call USER B then both can see each other in video for 20 sec then the receivers app goes into background while the caller see a freeze screen of the other user in his device. In both the case , the call continues .

Caller : see the freeze screen after 20 sec and the call continues
Receiver : app goes into background after 20 sec and the call continues

Can you please keep this open until the issue is confirmed to be resolved? We have spent so much time on this with no success.

You can easily deploy this code and do a test and advise us too.

[28th july_android 9 to 8_call.docx](https://github.com/twilio/video-quickstart-android/files/4990398/28th.july_android.9.to.8_call.docx)
[28th july_android 9 from 8_call recieve.docx](https://github.com/twilio/video-quickstart-android/files/4990399/28th.july_android.9.from.8_call.recieve.docx)
