### ISSUE TITLE
java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3003

### ISSUE THREAD

**Issue by ajaymalik05** [twilio/video-quickstart-android#513] opened 2020-05-14 19:58 UTC
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description
java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3003
getting this error after adding more than 15 participant in the room.App is keep crashing again & again.It is happening in multiple manufacturing device.
Please consider this issue on high priority.
[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```java
// Code that help reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces how Often

[What percentage of the time does it reproduce?]
100%
#### Logs
 java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at tvi.webrtc.EglBase14.createEglContext(EglBase14.java:279)
        at tvi.webrtc.EglBase14.<init>(EglBase14.java:76)
        at tvi.webrtc.EglBase.create(EglBase.java:91)
        at tvi.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:190)
        at tvi.webrtc.-$$Lambda$EglRenderer$F2SCIyfynnd5IMo2R-kIT2hSiis.run(Unknown Source:6)
        at tvi.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at tvi.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at tvi.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at tvi.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:184)
        at tvi.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196)
        at tvi.webrtc.EglRenderer.init(EglRenderer.java:181)
        at com.twilio.video.VideoTextureView.init(VideoTextureView.java:223)
        at com.twilio.video.VideoTextureView.init(VideoTextureView.java:208)
        at com.twilio.video.VideoTextureView.onAttachedToWindow(VideoTextureView.java:109)
        at android.view.View.dispatchAttachedToWindow(View.java:17453)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3336)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3336)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3336)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4981)
        at android.view.ViewGroup.addView(ViewGroup.java:4772)
        at android.view.ViewGroup.addView(ViewGroup.java:4712)
        at android.view.ViewGroup.addView(ViewGroup.java:4685)
        at com.odigolive.utils.ParticipantController.addThumb(ParticipantController.java:67)
        at com.odigolive.activities.VideoActivity.renderItemAsPrimary(VideoActivity.java:552)
        at com.odigolive.activities.VideoActivity.access$3800(VideoActivity.java:117)
        at com.odigolive.activities.VideoActivity$3.onDominantSpeakerChanged(VideoActivity.java:1486)
        at com.twilio.video.Video$2.onDominantSpeakerChanged(Video.java:206)
        at com.twilio.video.Room$1.lambda$onDominantSpeakerChanged$7$Room$1(Room.java:205)
        at com.twilio.video.-$$Lambda$Room$1$QFtPrZHdl_FBJwmDkSMQ1EYOh-0.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at tvi.webrtc.EglBase14.createEglContext(EglBase14.java:279)
        at tvi.webrtc.EglBase14.<init>(EglBase14.java:76)
        at tvi.webrtc.EglBase.create(EglBase.java:91)
        at tvi.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:190)
        at tvi.webrtc.-$$Lambda$EglRenderer$F2SCIyfynnd5IMo2R-kIT2hSiis.run(Unknown Source:6)
        at tvi.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at tvi.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at tvi.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-05-15 13:46:36.855 14297-14297/com.odigolive E/UncaughtException: java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at tvi.webrtc.EglBase14.createEglContext(EglBase14.java:279)
        at tvi.webrtc.EglBase14.<init>(EglBase14.java:76)
        at tvi.webrtc.EglBase.create(EglBase.java:91)
        at tvi.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:190)
        at tvi.webrtc.-$$Lambda$EglRenderer$F2SCIyfynnd5IMo2R-kIT2hSiis.run(Unknown Source:6)
        at tvi.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at tvi.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at tvi.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at tvi.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:184)
        at tvi.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196)
        at tvi.webrtc.EglRenderer.init(EglRenderer.java:181)
        at com.twilio.video.VideoTextureView.init(VideoTextureView.java:223)
        at com.twilio.video.VideoTextureView.init(VideoTextureView.java:208)
        at com.twilio.video.VideoTextureView.onAttachedToWindow(VideoTextureView.java:109)
        at android.view.View.dispatchAttachedToWindow(View.java:17453)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3336)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3336)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3336)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4981)
        at android.view.ViewGroup.addView(ViewGroup.java:4772)
        at android.view.ViewGroup.addView(ViewGroup.java:4712)
        at android.view.ViewGroup.addView(ViewGroup.java:4685)
        at com.odigolive.utils.ParticipantController.addThumb(ParticipantController.java:67)
        at com.odigolive.activities.VideoActivity.renderItemAsPrimary(VideoActivity.java:552)
        at com.odigolive.activities.VideoActivity.access$3800(VideoActivity.java:117)
        at com.odigolive.activities.VideoActivity$3.onDominantSpeakerChanged(VideoActivity.java:1486)
        at com.twilio.video.Video$2.onDominantSpeakerChanged(Video.java:206)
        at com.twilio.video.Room$1.lambda$onDominantSpeakerChanged$7$Room$1(Room.java:205)
        at com.twilio.video.-$$Lambda$Room$1$QFtPrZHdl_FBJwmDkSMQ1EYOh-0.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at tvi.webrtc.EglBase14.createEglContext(EglBase14.java:279)
        at tvi.webrtc.EglBase14.<init>(EglBase14.java:76)
        at tvi.webrtc.EglBase.create(EglBase.java:91)
        at tvi.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:190)
        at tvi.webrtc.-$$Lambda$EglRenderer$F2SCIyfynnd5IMo2R-kIT2hSiis.run(Unknown Source:6)
        at tvi.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at tvi.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at tvi.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
// Log output when issue occurs
```

### Versions

All relevant version information for issue.

#### Video Android SDK
5.5.0
[eg. 1.0.2]

#### Android API
minimum is 21 targeted is 29
[eg. 18]

#### Android Device
In multiple mobile manufacturer(All most in every device)
[eg. Nexus 5]

**Comment by aaalaniz** [comment] 2020-05-18 21:52
hey @ajaymalik05

Are you able to reproduce this issue in our [Video Collaboration App](https://github.com/twilio/twilio-video-app-android)?

Thanks!

**Comment by ajaymalik05** [comment] 2020-05-22 16:36
I didn't check with video collaboration App.But We have taken idea from the Video Collaboration App.

**Comment by aaalaniz** [comment] 2020-05-27 20:25
Hey @ajaymalik05 

Please attempt to reproduce this problem in the Video Collaboration app and provide a specific device model in case we need to investigate. I will close this issue for now as it's not actionable from the given information. We recently published a change to the collaboration app that uses a RecyclerView and ViewHolder pattern with the list of thumbnails. There was a bug previously that did not use the view holder pattern which may have caused this issue since each device has a finite number of EGL contexts available.

Thanks!

**Closed by aaalaniz** 2020-05-27 20:25 UTC
Labels: question

**Comment by ajaymalik05** [comment] 2020-05-28 12:02
Yeah i have seen updated code.Ok thanks for your support.

**Comment by altafcs** [comment] 2020-11-19 14:58
Its is still happening here are my details
Lenovo Tab M10 TB-X605F, Android 9, 3 GB RAM, Qualcomm Snapdragon 450
