### ISSUE TITLE
How to use flash with Camera 2?

### ISSUE THREAD

**Issue by S-Saagar** [twilio/video-quickstart-android#355] opened 2018-11-04 16:50 UTC
With below code done to on/off flash using camera1
-----------------------------------------------------------
if (enable) {
              camera1Capturer.updateCameraParameters(cameraParameters -> cameraParameters.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH));
            } else {
                camera1Capturer.updateCameraParameters(cameraParameters->
cameraParameters.setFlashMode(Camera.Parameters.FLASH_MODE_OFF));
            }
-----------------------------------------------------------
But in camera2 how to do that?

**Comment by aaalaniz** [comment] 2018-11-05 15:03
Duplicate of #146

**Closed by aaalaniz** 2018-11-05 15:03 UTC
