### ISSUE TITLE
Primary VideoView flashing and glitching, remote sometimes invisible, etc.

### ISSUE THREAD

**Issue by nkhar** [twilio/video-quickstart-android#471] opened 2020-01-26 18:18 UTC
### Description
When i ran sample code that connected to the room automatically without entering room numbers several problems occurred with the app. Most of them had to do with video views flashing and glitching on the primary view.

I came across several such issues, for instance: 
https://github.com/twilio/video-quickstart-android/issues/365 

This was caused because local video track was not yet created. App requests for permission, which is granted asynchronously. Basically user can establish a connection before this permission is granted. The code for creating local tracks is inside method that receives permission. If you establish connection before video track is created which happens only after permission is granted you will have flashing video view. This most likely won't occur in sample because user has to input room name before connection, time spent inputting the name is enough for tracks to be created.

This is not an issue, thought it might help other developers who were in a hurry and missed the fact that permissions for using camera are received asynchronously.

**Comment by aaalaniz** [comment] 2020-01-28 15:26
Hey @nkhar 

Thank you for the detailed description. I looked at the quickstart code and it does appear that the steps you provided would result in flickering with the correct timing. I will mark this issue as a quickstart bug and we will fix it.

Thank you!

**Comment by aaalaniz** [comment] 2020-03-02 23:45
Hey @nkhar 

We double checked the quickstart and found that we could not reproduce in an unmodified quickstart. I will close this issue for now.

If you are interested in a more full featured application [I recommend you visit our Twilio Video Android App](https://github.com/twilio/twilio-video-app-android).

Thanks!

**Closed by aaalaniz** 2020-03-02 23:45 UTC
Labels: bug
