### ISSUE TITLE
Broadcast system audio like iOS

### ISSUE THREAD

**Issue by nickoli58** [twilio/video-quickstart-android#369] opened 2018-12-26 05:26 UTC
It seems it’s not possible on android to broadcast audio from other apps on the system during a screencast like it is on the iOS SDK example. Is that true? Thank you

**Comment by aaalaniz** [comment] 2019-01-02 17:17
Hey @nickoli58 

You are correct. The Video Android SDK does not support custom audio devices which would enable sharing audio from sources other than the microphone.

What kind of use case are you trying to build?

Thanks!

**Comment by nickoli58** [comment] 2019-01-02 18:21
Thanks, looking to record the audio coming from other apps like you can with iOS. Is it not possible because of the video SDK or limitations in android itself? Thank you

**Comment by aaalaniz** [comment] 2019-01-02 21:31
Hey @nickoli58 

I don't know of an API that allows capturing audio from other applications on Android. If there is such an API, then the Video Android SDK is the only limitation because we do not support using a custom audio device.

**Comment by nickoli58** [comment] 2019-01-02 23:00
Thank you, do you plan to add support for custom audio devices to bring the android SDK up to parity with  IOS?

**Comment by aaalaniz** [comment] 2019-01-03 20:42
Hey @nickoli58 

I don't have a timeline, but yes, we do plan on adding custom audio devices to the Video Android SDK.

Thanks!

**Comment by guruaugust** [comment] 2019-12-12 07:34
hi @aaalaniz how can we publish audio while screen capturing using android SDK please help.

**Comment by aaalaniz** [comment] 2019-12-17 19:30
Hey @guruaugust 

Publishing audio and a screen video track can be done by performing the following:

1. Create an audio track
2. Create a video track with a ScreenCapturer (I recommend referencing the [ScreenCapturer example](https://github.com/twilio/video-quickstart-android/tree/master/exampleScreenCapturer) for proper guidance)
3. Connect to a Room with the audio and video track.

Please open a separate issue if you need further assistance.

Thank you

**Comment by aaalaniz** [comment] 2020-04-15 15:54
Duplicate of #353

**Closed by aaalaniz** 2020-04-15 15:54 UTC
Labels: enhancement
