### ISSUE TITLE
Soft sound on Samsung device running android 11

### ISSUE THREAD

**Issue by khoamt** [twilio/video-quickstart-android#605] opened 2021-01-11 09:29 UTC
### Description

Sound is too soft on the remote participant side, it works well on android 10 but sound is soft after upgrading to android 11 on Samsung Note 20 Ultra and Samsung S20 series using Android 11.

### Steps to Reproduce

1. Using Samsung Note 20 Ultra as a local participant. Remote participant is Samsung Galaxy S9
2. Make a call
3. Sound is too soft on remote participant side.

#### Expected Behavior

Sound should loud.

#### Actual Behavior

Sound is soft in web or Samsung Galaxy S9

#### Reproduces how Often

All the time

#### Video Android SDK

5.13.0

#### Android API

Android target API 29

#### Android Device

Samsung Galaxy Note 20 Ultra

**Comment by Alton09** [comment] 2021-01-14 00:09
Hi @khoamt . Thanks for reaching out regarding this issue. Are both of these devices running the Android SDK? I noticed you mentioned "web" under **Actual Behavior**.

**Comment by khoamt** [comment] 2021-01-14 00:50
Hi @Alton09, I also tested with the web and android devices as remote participants. This issue also happened. Thanks

**Comment by khoamt** [comment] 2021-01-20 07:32
Hi @Alton09 Could you take a look at this issue as we face a lot of cases on Samsung flag ship running android 11?
Here are some devices: Samsung Note 20 series, Samsung S20 series. I tried https://github.com/twilio/video-quickstart-android#troubleshooting-audio but still can't help. Thanks

**Comment by Alton09** [comment] 2021-01-20 22:57
Hi @khoamt . Are you using [AudioSwitch](https://github.com/twilio/audioswitch) to manage audio input/output in your app? With this library, you can easily select speakerphone to help increase the volume on the receiving device.

**Comment by khoamt** [comment] 2021-01-25 02:51
@Alton09 Yes, I am using AudioSwitch select audio device when in video call. Seems this issue happens when user is using speaker phone. The other input like wired headset or bluetooth are ok.

**Comment by Alton09** [comment] 2021-01-25 18:29
@khoamt Can you please share your app's Logcat logs with [logging enabled](https://twilio.github.io/audioswitch/latest/audioswitch/com.twilio.audioswitch/-audio-switch/-audio-switch.html) and `AS/` logcat filter applied? This can help us troubleshoot a bit further. I suspect that the device is not activating speakerphone properly and audio is routing to the earpiece. Thanks!

**Comment by khoamt** [comment] 2021-01-26 04:25
Hi @Alton09, here are logs

```
2021-01-26 11:21:10.123 27151-27151/app.package.name D/AS/AudioSwitch: AudioSwitch(1.0.1)
2021-01-26 11:21:10.130 27151-27151/app.package.name D/AS/AudioDeviceManager: Earpiece available
2021-01-26 11:21:10.134 27151-27151/app.package.name D/AS/AudioDeviceManager: Speakerphone available
2021-01-26 11:21:10.134 27151-27151/app.package.name D/AS/AudioSwitch: Available AudioDevice list updated: [Earpiece(name=Earpiece), Speakerphone(name=Speakerphone)]
2021-01-26 11:21:10.134 27151-27151/app.package.name D/AS/AudioDeviceManager: Earpiece available
2021-01-26 11:21:10.134 27151-27151/app.package.name D/AS/AudioDeviceManager: Speakerphone available
2021-01-26 11:21:10.134 27151-27151/app.package.name D/AS/AudioSwitch: Available AudioDevice list updated: [Earpiece(name=Earpiece), Speakerphone(name=Speakerphone)]
2021-01-26 11:21:10.357 27151-27151/app.package.name W/AS/BluetoothHeadsetManager: Cannot deactivate when in the com.twilio.audioswitch.bluetooth.BluetoothHeadsetManager$HeadsetState$Disconnected@dd9aa21 state
2021-01-26 11:21:10.727 27151-27151/app.package.name D/AS/WiredHeadsetReceiver: Wired headset device  disconnected
2021-01-26 11:21:10.727 27151-27151/app.package.name D/AS/AudioDeviceManager: Earpiece available
2021-01-26 11:21:10.728 27151-27151/app.package.name D/AS/AudioDeviceManager: Speakerphone available
2021-01-26 11:21:10.728 27151-27151/app.package.name D/AS/AudioSwitch: Available AudioDevice list updated: [Earpiece(name=Earpiece), Speakerphone(name=Speakerphone)]
2021-01-26 11:21:10.728 27151-27151/app.package.name W/AS/BluetoothHeadsetManager: Cannot deactivate when in the com.twilio.audioswitch.bluetooth.BluetoothHeadsetManager$HeadsetState$Disconnected@dd9aa21 state
2021-01-26 11:21:38.163 27151-27151/app.package.name W/AS/BluetoothHeadsetManager: Cannot deactivate when in the com.twilio.audioswitch.bluetooth.BluetoothHeadsetManager$HeadsetState$Disconnected@dd9aa21 state

```
Thanks

**Comment by Alton09** [comment] 2021-01-26 18:57
Hi @khoamt Thanks for sharing the logs. Are these the logs coming from the device that has quite audio? If so, it looks like the `Earpeice` is being automatically selected. You can instead have the library automatically select the `Speakerphone` by passing the following list into the AudioSwitch constructor:

`val audioSwitch = AudioSwitch(application, preferredDeviceList = listOf(Speakerphone::class.java))`

**Comment by khoamt** [comment] 2021-01-27 04:16
@Alton09 Thanks for answer. Are these the logs coming from the device that has quite audio? -> Yes. I'm using AudioSwitch 1.0.1 and I select `Speakerphone` as default when video call starts. I also updated to AudioSwitch 1.1.1 and set `preferredDeviceList = listOf(Speakerphone::class.java)` but still have the same issue.

**Comment by Alton09** [comment] 2021-01-27 18:12
Thanks for the update @khoamt. I'll try to run some tests to see if I can reproduce the behavior.

**Comment by Alton09** [comment] 2021-01-28 23:15
Hi @khoamt . We have verified that this issue does not occur using the [Twilio Video App](https://github.com/twilio/twilio-video-app-android) on a Samsung Note 20 Ultra. It may be worth taking a look in the app so see how AudioSwitch is being used as there could be a missed step in your app.

**Comment by Alton09** [comment] 2021-02-03 17:51
Closing this one for now. Please feel free to reach out if you are still experiencing issues. Thanks!

**Closed by Alton09** 2021-02-03 17:51 UTC
Labels: bug
