### ISSUE TITLE
AudioSink Compatibility with Custom AudioDevice

### ISSUE THREAD

**Issue by cyodrew** [twilio/video-quickstart-android#736] opened 2023-01-19 19:43 UTC
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

Adding an `AudioSink` on an `AudioTrack` does not seem to work when using a custom `AudioDevice`. By default, the `DefaultAudioDevice` is used by the system if one isn't specified and `AudioSink` callback works as expected. Are these features not compatible?

### Steps to Reproduce

1. Create an `AudioDevice` and add it to the Room prior to connecting via `Video.setAudioDevice`
2. Add an `AudioSink` to an `AudioTrack`
3. Observe that the callback `renderSample` is not invoked after connecting to the Room.

#### Code

This can be recreated by adding an AudioSink to the example custom audio device [project](https://github.com/twilio/video-quickstart-android/tree/master/exampleCustomAudioDevice).

#### Expected Behavior

The `renderSample` callback is invoked.

#### Actual Behavior

The `renderSample` callback is not invoked.

#### Reproduces how Often

100%

#### Logs

N/A

### Versions

N/A

#### Video Android SDK

7.3.1

#### Android API

33

#### Android Device

Pixel 7 Pro

**Comment by afalls-twilio** [comment] 2023-03-16 22:53
Thank you for the detailed bug report. We are in the midst of a significant release (upgrading webrtc) and as soon as that is complete we will verify if this is still an issue. Feel free to verify yourself upon the release.

**Comment by ocarevs** [comment] 2023-04-11 11:24
Hi @cyodrew the issue is fixed with the Video Android SDK 7.6.1, works as expected and callbacks from the AudioSink are invoked when using custom AudioDevice. cc @afalls-twilio

**Closed** 2023-04-11 15:06 UTC
