### ISSUE TITLE
Add remote video track to custom render cause crash

### ISSUE THREAD

**Issue by itayloryan** [twilio/video-quickstart-android#227] opened 2018-01-15 06:28 UTC
### Add remote video track to custom render cause crash

All the code is from exampleCustomVideoRenderer and quickstart

### Steps to Reproduce

1. Integrate the SnapshotVideoRender
2. When remote video track subscribed, add to this custom render
3. app crashed

```
    @Override
    public void renderFrame(final I420Frame i420Frame) {
        // Capture bitmap and post to main thread
        if (snapshotRequsted.compareAndSet(true, false)) {
            /*
             * I420Frame can be represented as texture or an in-memory buffer. yuvPlanes is not
             * null and textureId is zero when frame is represented in memory and yuvPlanes is
             * null textureId is a non zero value when the frame is represented as a texture.
             */
            final Bitmap bitmap = i420Frame.yuvPlanes == null ?
                    captureBitmapFromTexture(i420Frame) :
                    captureBitmapFromYuvFrame(i420Frame);
            handler.post(new Runnable() {
                @Override
                public void run() {
                    // Update the bitmap of image view
                    imageView.setImageBitmap(bitmap);

                    // Frames must be released after rendering to free the native memory
                    i420Frame.release();
                }
            });
        } else {
            i420Frame.release();
        }
    }


 private Bitmap captureBitmapFromTexture(I420Frame i420Frame) {
        int width = i420Frame.rotatedWidth();
        int height = i420Frame.rotatedHeight();
        int outputFrameSize = width * height * 3 / 2;
        ByteBuffer outputFrameBuffer = ByteBuffer.allocateDirect(outputFrameSize);
        final float frameAspectRatio = (float) i420Frame.rotatedWidth() /
                (float) i420Frame.rotatedHeight();
        final float[] rotatedSamplingMatrix =
                RendererCommon.rotateTextureMatrix(i420Frame.samplingMatrix,
                        i420Frame.rotationDegree);
        final float[] layoutMatrix = RendererCommon.getLayoutMatrix(false,
                frameAspectRatio,
                (float) width / height);
        final float[] texMatrix = RendererCommon.multiplyMatrices(rotatedSamplingMatrix,
                layoutMatrix);
        /*
         * YuvConverter must be instantiated on a thread that has an active EGL context. We know
         * that renderFrame is called from the correct render thread therefore
         * we defer instantiation of the converter until frame arrives.
         */
        YuvConverter yuvConverter = new YuvConverter();
        yuvConverter.convert(outputFrameBuffer,
                width,
                height,
                width,
                i420Frame.textureId,
                texMatrix);

        // Now we need to unpack the YUV data into planes
        byte[] data = outputFrameBuffer.array();
        int offset = outputFrameBuffer.arrayOffset();
        int stride = width;
        ByteBuffer[] yuvPlanes = new ByteBuffer[] {
                ByteBuffer.allocateDirect(width * height),
                ByteBuffer.allocateDirect(width * height / 4),
                ByteBuffer.allocateDirect(width * height / 4)
        };
        int[] yuvStrides = new int[] {
                width,
                (width + 1) / 2,
                (width + 1) / 2
        };

        // Write Y
        yuvPlanes[0].put(data, offset, width * height);

        // Write U
        for (int r = height ; r < height * 3 / 2; ++r) {
            yuvPlanes[1].put(data, offset + r * stride, stride / 2);
        }

        // Write V
        for (int r = height ; r < height * 3 / 2 ; ++r) {
            yuvPlanes[2].put(data, offset + r * stride + stride / 2, stride / 2);
        }

        // Convert the YuvImage
        YuvImage yuvImage = i420ToYuvImage(yuvPlanes, yuvStrides, width, height);

        ByteArrayOutputStream stream = new ByteArrayOutputStream();
        Rect rect = new Rect(0, 0, yuvImage.getWidth(), yuvImage.getHeight());

        // Compress YuvImage to jpeg
        yuvImage.compressToJpeg(rect, 100, stream);

        // Convert jpeg to Bitmap
        byte[] imageBytes = stream.toByteArray();

        // Release YUV Converter
        yuvConverter.release();

        return BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.length);
    }
```

#### Expected Behavior

Get the remote video snapshot

#### Actual Behavior

App crashed

#### Reproduces how Often

Always

#### Logs

```
01-15 14:22:16.766 8103-8339/com.tacitwear W/System.err: java.lang.RuntimeException: glCreateShader() failed. GLES20 error: 0
01-15 14:22:16.766 8103-8339/com.tacitwear W/System.err:     at org.webrtc.GlShader.compileShader(GlShader.java:24)
01-15 14:22:16.766 8103-8339/com.tacitwear W/System.err:     at org.webrtc.GlShader.<init>(GlShader.java:42)
01-15 14:22:16.766 8103-8339/com.tacitwear W/System.err:     at org.webrtc.YuvConverter.<init>(YuvConverter.java:118)
01-15 14:22:16.766 8103-8339/com.tacitwear W/System.err:     at com.tacitwear.widget.SnapshotVideoRenderer.captureBitmapFromTexture(SnapshotVideoRenderer.java:92)
01-15 14:22:16.766 8103-8339/com.tacitwear W/System.err:     at com.tacitwear.widget.SnapshotVideoRenderer.renderFrame(SnapshotVideoRenderer.java:48)
01-15 14:22:16.766 8103-8339/com.tacitwear W/System.err:     at com.twilio.video.VideoTrack$VideoRendererCallbackAdapter.renderFrame(VideoTrack.java:166)
```

### Versions

All relevant version information for issue.

#### Video Android SDK

2.0.0-preview8 / 2.0.0-preview7

#### Android API

19 / 24

#### Android Device

Samsung tab S4
Huawei Honor AGS W09

**Comment by aaalaniz** [comment] 2018-01-15 15:59
Hey @itayloryan 

This issue is a duplicate of #213 

Can you elaborate on your use case in #213 ?

Thanks!

**Comment by itayloryan** [comment] 2018-01-16 00:44
Thank you @aaalaniz 
Actually I have tried on your answers from the issue already exists, but dose not work for me. Below is the log after I move the i420frame capture to main thread, still crashed. Can you help to troubleshot?

```
 @Override
    public void renderFrame(final I420Frame i420Frame) {
        // Capture bitmap and post to main thread
        if (snapshotRequsted.compareAndSet(true, false)) {

            handler.post(new Runnable() {
                @Override
                public void run() {
                    /*
                     * I420Frame can be represented as texture or an in-memory buffer. yuvPlanes is not
                     * null and textureId is zero when frame is represented in memory and yuvPlanes is
                     * null textureId is a non zero value when the frame is represented as a texture.
                     */
                    final Bitmap bitmap = i420Frame.yuvPlanes == null ?
                            captureBitmapFromTexture(i420Frame) :
                            captureBitmapFromYuvFrame(i420Frame);
                    // Update the bitmap of image view
                    imageView.setImageBitmap(bitmap);

                    // Frames must be released after rendering to free the native memory
                    i420Frame.release();
                }
            });
        } else {
            i420Frame.release();
        }
    }
```

 ```
                                                    --------- beginning of crash
01-16 08:39:55.759 4772-4772/com.tacitwear E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.tacitwear, PID: 4772
                                                             java.lang.RuntimeException: glCreateShader() failed. GLES20 error: 0
                                                                 at org.webrtc.GlShader.compileShader(GlShader.java:24)
                                                                 at org.webrtc.GlShader.<init>(GlShader.java:42)
                                                                 at org.webrtc.YuvConverter.<init>(YuvConverter.java:118)
                                                                 at com.tacitwear.widget.SnapshotVideoRenderer.captureBitmapFromTexture(SnapshotVideoRenderer.java:93)
                                                                 at com.tacitwear.widget.SnapshotVideoRenderer.access$000(SnapshotVideoRenderer.java:29)
                                                                 at com.tacitwear.widget.SnapshotVideoRenderer$1.run(SnapshotVideoRenderer.java:52)
                                                                 at android.os.Handler.handleCallback(Handler.java:761)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                 at android.os.Looper.loop(Looper.java:156)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6595)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

```

**Comment by aaalaniz** [comment] 2018-01-16 00:49
I'll have a look tomorrow. Thanks for the logs!

**Comment by itayloryan** [comment] 2018-01-16 00:52
@aaalaniz Thank you, have a nice rest

**Comment by aaalaniz** [comment] 2018-01-16 15:52
Hey @itayloryan 

I'm investigating your issue today and I need a little more information about your use case. Are you rendering the remote video to a `VideoView` **and** writing a custom renderer that extracts the frame? Or are you trying to just extract the frame in a custom renderer? Please provide answers to the following:

1. Are you rendering local video in your app? (ie video from camera)
2. Are you rendering remote video in your app?
3. What type of custom renderer are you interested in?

The reason that I need more information is the issue you have encountered is a known threading bug captured in #213 . `renderFrame` is called on a thread different from the thread with an EGL context. There is a workaround, but I need to know more about your app before I can provide something that should work for you.

Thanks!

**Comment by itayloryan** [comment] 2018-01-17 01:51
Thank you @aaalaniz, the custom render is from the demo code in exampleCustomVideoRenderer.
Below is my use case:
1. I do render local video in my app, this is for one of the participant(caller1) in the video session, he/she provide video to another caller(caller 2).
2. I do render the remote video in my app, this is for caller 2, just render to display the remote video from caller 1.  If caller 1 get a snapshot from the local video render, caller 2 will also get a snapshot from the remote video track, this will cause the crash.

BTW, I tried this use case in both Android phone, and it works fine, the crash only happen when run on an Android tablet.

Thank you!

**Comment by aaalaniz** [comment] 2018-01-18 16:30
Hey @itayloryan 

Apologies for the delayed response. Here is a [gist](https://gist.github.com/aaalaniz/1d3c223ff5a6d9fc58598a995085049b) that may help you with the workaround you need. I have changed `SnapshotVideoRenderer` to extend `VideoView`. Extending `VideoView` ensures that `renderFrame` is called on a thread with an EGLContext and hopefully resolves the crash you are seeing.

Let me know if this works. Thanks!

**Closed** 2019-02-07 21:47 UTC
Labels: duplicate
