### ISSUE TITLE
Using Custom  Video Source for the Video Background Replacement in Twilio

### ISSUE THREAD

**Issue by Sujith-PS** [twilio/video-quickstart-android#507] opened 2020-05-06 04:41 UTC
Is it possible to use a custom camera source instead of using the camera source from the SDK when
initializing the localvideo track

cameraCapturer = new CameraCapturer(this, CameraSource.FRONT_CAMERA);
LocalVideoTrack localVideoTrack = LocalVideoTrack.create(context, true, cameraCapturer);

My usecase is to add a background/bokhe effect to the video before it is rendering on the view.So the user have a control over this.like he can turn on /off his background blurring.So i though about modifying the camerasource before it is giving to a localvideotrack.I saw most of the cameracapture functions expecting a camerasource of type same from the SDK.Can you recommend some suggestions for this

**Comment by aaalaniz** [comment] 2020-05-07 22:25
Duplicate of [Video App #83](https://github.com/twilio/twilio-video-app-android/issues/83)

**Closed by aaalaniz** 2020-05-07 22:25 UTC
