### ISSUE TITLE
Failed to create EGL context: 0x3003

### ISSUE THREAD

**Issue by Myeongwon-Kang** [twilio/video-quickstart-android#357] opened 2018-11-06 07:30 UTC
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

Fatal Exception: java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3003

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```java
// Code that help reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces how Often

[What percentage of the time does it reproduce?]

#### Logs

at org.webrtc.EglBase14.createEglContext(EglBase14.java:279)
       at org.webrtc.EglBase14.<init>(EglBase14.java:76)
       at org.webrtc.EglBase$-CC.create(EglBase.java:91)
       at org.webrtc.EglRenderer.lambda$init$0(EglRenderer.java:190)
       at org.webrtc.-$$Lambda$EglRenderer$A5MPsBufyTiKpmjvPS46Dr9iaHs.run(lambda)
       at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
       at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
       at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
       at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:184)
       at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196)
       at org.webrtc.EglRenderer.init(EglRenderer.java:181)
       at org.webrtc.SurfaceEglRenderer.init(SurfaceEglRenderer.java:61)
       at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:88)
       at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:72)
       at com.twilio.video.VideoView.setupRenderer(VideoView.java:178)
       at com.twilio.video.VideoView.onAttachedToWindow(VideoView.java:90)
       at android.view.View.dispatchAttachedToWindow(View.java:13621)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2727)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4010)
       at android.view.ViewGroup.addView(ViewGroup.java:3821)
       at android.view.ViewGroup.addView(ViewGroup.java:3762)
       at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:778)
       at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
       at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8222)
       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8180)
       at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8168)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1573)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
       at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1333)
       at android.support.v7.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1065)
       at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4956)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
       at android.view.Choreographer.doCallbacks(Choreographer.java:586)
       at android.view.Choreographer.doFrame(Choreographer.java:555)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

### Versions

All relevant version information for issue.

#### Video Android SDK

3.0.0

#### Android API

android os 5.1 and android os 5.1.1

#### Android Device

LG V10 and LG G4

**Comment by aaalaniz** [comment] 2018-11-06 14:54
Duplicate of #292

**Closed by aaalaniz** 2018-11-06 14:54 UTC
