### ISSUE TITLE
NullPointerException in Camera2Capturer.switchCamera

### ISSUE THREAD

**Issue by palicka** [twilio/video-quickstart-android#419] opened 2019-06-27 16:46 UTC
Hi, we have this crash log in crashlytics, I tried to reproduce it myself, but with no luck.

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.webrtc.Camera2Capturer.switchCamera(java.lang.String, org.webrtc.CameraVideoCapturer$CameraSwitchHandler)' on a null object reference
>        at com.twilio.video.Camera2Capturer.switchCamera + 327(Camera2Capturer.java:327)

Bug was present in Android versions 6,7,8,9,
brands: huawei, samsung, LG,motorola..

it happens when > `cameraCapturerCompat.switchCamera()` is called
`camera2Capturer` in `CameraCaptureCompat` is null 
we use version 4.1.1.  
Thanks

**Comment by zackm0571** [comment] 2019-06-27 17:51
Hey @palicka thanks for reaching out. I'll be looking into this further. Do you happen to have more detailed logs from just before the crash event?

**Comment by palicka** [comment] 2019-06-27 18:18
@zackm0571 thanks for the quick response. Unfortunately, I don't have any more information.

**Comment by zackm0571** [comment] 2019-07-16 18:19
Hey @palicka is this still reproducing often for you guys? We haven't been able to reproduce this on our end.

**Comment by palicka** [comment] 2019-07-16 18:35
Hi @zackm0571 , yes it's still an issue...

**Comment by zackm0571** [comment] 2019-07-16 18:48
@palicka we're going to gather more details and work closely with our QA team this sprint to triage. Thanks for your patience.

**Comment by zackm0571** [comment] 2019-07-18 21:17
Hey @palicka could you provide a list of devices that you're seeing this crash on?

**Comment by palicka** [comment] 2019-07-18 21:30
Hi, sure. There are 36 types of Samsung devices (Galaxy S7 edge 4%,Galaxy S10+ 4%,Galaxy S9+,48% ,Other (33)
Huawei:  nova 3i 3%, HUAWEI Y7 Prime 2018 3%, HUAWEI Y9 2019, 23% Other (20)
Motorola,LG and Sony

crashes in total: Samsung 60%, Huawei 31%, other 9%

and OS versions: 9,8,7,6 (min is 6)

**Comment by aaalaniz** [comment] 2019-07-24 00:03
hey @palicka 

I've been looking at this bug and could not reproduce. However, I do have some follow up comments and questions. Do you mind clarifying the following?

>it happens when > cameraCapturerCompat.switchCamera() is called
camera2Capturer in CameraCaptureCompat is null
we use version 4.1.1.

Looking at the stack trace, it appears that camera2Capturer in Camera2Capturer is `null`. If you can provide any additional logs from Crashlytics that would be helpful. Do you happen to know the user scenario under which the crash occurred? For example, is the user just performing a standard camera switch while in the application or are there other steps the user performs prior to switching the camera. I'm looking at our source code and I see what might be a race condition between tearing down the Camera2Capturer and switching the Camera, but I'll need more details to confirm.

I appreciate your patience as we work through this issue.

Thanks!

**Comment by palicka** [comment] 2019-07-25 18:36
Hi @aaalaniz,
well, 'cameraCapturerCompat' is instance of 'CameraCaptureCompat' and when 'switchCamera()' is called, NPE is thrown. I don't know why and when...
and as I said before, unfortunately I'm not able to provide any more additional information and I can't reproduce it either.

thank you for not giving up on me :)

**Comment by aaalaniz** [comment] 2019-07-31 22:32
Hey @palicka 

I did another round of triaging and I am unable to reproduce. I am beginning to suspect the problem is within the `CameraCapturerCompat` code itself rather than in the SDK. Unfortunately, we currently do not have test coverage for `CameraCapturerCompat`. 

As a workaround, I recommend using the `CameraCapturer`. I will close this issue as it's not actionable for our team at the moment. If you find any issues specific issues in `CameraCapturer` or `Camera2Capturer` please file or reopen an issue with debug logs and/or steps to reproduce.

Thank you.

**Closed by aaalaniz** 2019-07-31 22:32 UTC
