### ISSUE TITLE
rotate local video view

### ISSUE THREAD

**Issue by theothersideofgod** [twilio/video-quickstart-android#525] opened 2020-06-11 03:10 UTC
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-android/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/android)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

[Description of the issue]
I try to rotate local video view by setting the cameraParamterUpdater on first frame available, but it not working. should use other way? or I just call function on wrong place? thanks
### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```java
// Code that help reproduce the issue
   private void createLocalMedia(boolean enableAudio, boolean enableVideo) {
        // Share your microphone
        localAudioTrack = LocalAudioTrack.create(getContext(), enableAudio);

        // Share your camera
        cameraCapturer = this.createCameraCaputer(getContext(), CameraCapturer.CameraSource.BACK_CAMERA);

        if (cameraCapturer == null){
            cameraCapturer = this.createCameraCaputer(getContext(), CameraCapturer.CameraSource.BACK_CAMERA);
        }
        if (cameraCapturer == null){
            WritableMap event = new WritableNativeMap();
            event.putString("reason", "No camera is supported on this device");
            pushEvent(CustomTwilioVideoView.this, ON_CONNECT_FAILURE, event);
            return;
        }

        if (cameraCapturer.getSupportedFormats().size() > 0) {

            localVideoTrack = LocalVideoTrack.create(getContext(), enableVideo, cameraCapturer, buildVideoConstraints());
            if (thumbnailVideoView != null && localVideoTrack != null) {
                localVideoTrack.addRenderer(thumbnailVideoView);
            }
            setThumbnailMirror();
        }



        Boolean result = cameraCapturer.updateCameraParameters(new CameraParameterUpdater() {
            @Override
            public void apply(@NonNull Camera.Parameters cameraParameters) {
                cameraParameters.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH);
                cameraParameters.setRotation(180);
            }
        });



        Log.i("updateresult", ""+result+deg);

        connectToRoom(enableAudio);
    }

```

#### Expected Behavior

Other participant still see the right direction of stream after user upside down his own phone.

#### Actual Behavior

didn't rotate.

#### Reproduces how Often

setRotation not working, follow the android quick start setting. 

#### Logs

```
// Log output when issue occurs
```

### Versions

All relevant version information for issue.

#### Video Android SDK

[eg. 1.0.2]

#### Android API

26

#### Android Device

sumsung c-8000

**Comment by aaalaniz** [comment] 2020-06-12 16:23
Hey @theothersideofgod 

Can you provide a little more details as to what you are trying to accomplish? A sample code project for us to investigate would be helpful too. The quickstarts and Video Collaboration app should handle device rotations.

What is the expected behavior when you update the camera rotation?

Thanks!

**Comment by theothersideofgod** [comment] 2020-06-12 17:00
hi, @aaalaniz 
Thanks for your reply.
we have a situation that we need upside down the phone(face camera on the bottom) when user uses the twilio video call.
if we upside down the phone, other participant will see upside down video stream.
is it possible to rotate the video stream? so that participant will see right video.
i try to use parameter.setRotate but not working.
Thank again.

**Comment by theothersideofgod** [comment] 2020-06-18 01:28
Hi @aaalaniz, any updates on this?

**Comment by aaalaniz** [comment] 2020-06-24 01:20
Hey @theothersideofgod 

Apologies for the delayed response. I have a bit of a silly question, but did you try removing the call to `cameraParameters.setRotation(180);`? 

I double checked the SDK code and both capturers should account for device rotation and camera orientation to ensure that the captured image is oriented correctly.

Thanks!

**Comment by theothersideofgod** [comment] 2020-06-24 02:27
Hi @aaalaniz 
I am not trying to remove it, i am trying to add it so video appears upside down.
my question is when i try to setRotation(180)to rotate the video, it's not working.
did i miss anything? need extra setting?

**Comment by aaalaniz** [comment] 2020-06-24 02:55
Hey @theothersideofgod 

Thank you for the clarification. Have you tried setting [android:screenOrientation](https://developer.android.com/guide/topics/manifest/activity-element.html#screen) to `reversePortrait`? I'm not sure if this covers your use case entirely but it does seem like it will force the activity to show the view right side up when the device is upside down. 

Thanks!

**Comment by theothersideofgod** [comment] 2020-06-24 16:45
hi, @aaalaniz 
is Android have some kind of setting like iOS could do rotate video view? 
https://github.com/twilio/video-quickstart-ios/issues/324#issuecomment-447406538
thanks

**Comment by aaalaniz** [comment] 2020-06-30 21:59
Hey @theothersideofgod 

Did specifying the `screenOrientation` not provide the desired experience? Maybe I am not understanding your use case correctly. My current understanding is that your users need to use your app with the device upside down (camera on bottom) and the user on the other side should see the correctly oriented video. Can you provide a screenshot of both sides of the experience?

- Screenshot that shows the UI from the user with the upside down device
- Screenshot that shows the received video from the user with an upside down device.

Thanks!

**Comment by theothersideofgod** [comment] 2020-07-03 07:16
Hi, @aaalaniz 

Thank you for your help

if i set screenOrientation to reversePortrait, whole app will upside down.

but i only need the screen rotate to upside down on video calling screen.

below is the screen shot don't know it's clear or not.

[https://www.screencast.com/t/As4EOuw8Z](url)

**Comment by aaalaniz** [comment] 2020-07-15 16:11
Hey @theothersideofgod 

If you are not able to dynamically update the screenOrientation for your use case then unfortunately you have to resort to something like the following class.

```
class RotatedCameraCapturer(context: Context, cameraSource: CameraSource) :
    CameraCapturer(context, cameraSource) {

    override fun startCapture(
        captureFormat: VideoFormat,
        videoCapturerListener: VideoCapturer.Listener
    ) {
        val rotateFrameProxyListener: VideoCapturer.Listener = object : VideoCapturer.Listener {
            override fun onCapturerStarted(success: Boolean) {
                videoCapturerListener.onCapturerStarted(success)
            }

            override fun onFrameCaptured(videoFrame: VideoFrame) {
                /*
                 * Update the orientation of the frame using reflection and then report the
                 * frame to VideoCapturer.Listener. This logic may need to be updated to apply a
                 * 180 degree flip from the original orientation instead of just setting the
                 * rotation angle to 180.
                 */
                val orientationField: Field = VideoFrame::class.java.getDeclaredField("orientation")
                orientationField.setAccessible(true)
                orientationField.set(videoFrame, VideoFrame.RotationAngle.ROTATION_180)
                videoCapturerListener.onFrameCaptured(videoFrame)
            }
        }

        super.startCapture(captureFormat, rotateFrameProxyListener)
    }
}
```

I have not validated this code, but it's a decent starting point. Basically you would need to perform the following:

1. Subclass the CameraCapturer class
2. Override the `startCapture` method and proxy the calls to `VideoCapturer.Listener` with a "rotated" frame. I provided a simple example of how to do this using reflection.
3. Since this approach updates the orientation of the frame for both local and remote rendering then you will most likely need to write a custom local VideoRenderer that updates the rotation value of the `I420Frame` before sending to a `VideoView` or `VideoTextureView`.

**Comment by aaalaniz** [comment] 2020-07-24 20:00
Hey @theothersideofgod 

Were you able to use this code to resolve your issue?

Thanks!

**Comment by aaalaniz** [comment] 2020-08-19 22:08
Hey @theothersideofgod 

I am closing this issue. Please reopen if you have any follow up questions or comments.

Thanks!

**Closed by aaalaniz** 2020-08-19 22:08 UTC
Labels: question
