### ISSUE TITLE
Getting a black screen while rendering remote videotrack.

### ISSUE THREAD

**Issue by shivthepro** [twilio/video-quickstart-android#218] opened 2017-12-27 12:54 UTC
After the participant is joined I tried to render the remote participant's video in the VideoView. Im getting a black screen for almost 5-7secs before Im able to see the remote participant's video on my screen.

If there is a call back in videoview like first frame is available then Ill be able to show some placeholder in place until the black screen is being shown.

**Comment by aaalaniz** [comment] 2017-12-27 15:34
Hey @shivthepro 

What version of the SDK are you using?

Thanks!

**Comment by shivthepro** [comment] 2017-12-27 17:52
It's 2.0.0-preview4..

**Comment by shivthepro** [comment] 2017-12-27 18:45
Just tried with preview7 sdk too it has the same problem

**Comment by aaalaniz** [comment] 2017-12-28 03:10
Hey @shivthepro 

I recommend calling `setListener` on `VideoView`. There is an `onFirstFrameRendered` callback that will help you with the delayed video. However, I would like to investigate this delay further. Are you using a group room? Can you provide a Room SID where you see this behavior?

Thanks!

**Comment by shivthepro** [comment] 2017-12-28 06:36
Hey @aaalaniz Im using this VideoView backed by TextureView https://gist.github.com/aaalaniz/bfbc4891c98ef3b23558ff2260cbcc8e it does not contain a setListener method. Please add the method to it. Ill check it.

I will get you the SID soon.

Thanks 👍

**Comment by sathishvgs** [comment] 2017-12-28 10:27
Hi @aaalaniz,  In iOS[swift] also I'm facing the same issue.

**Comment by aaalaniz** [comment] 2017-12-28 20:09
Hey @shivthepro 

I added a setListener method.

Thanks!

**Comment by shivthepro** [comment] 2018-01-19 11:12
Hey @aaalaniz 
Here are the room details to sort out the black screen issue
   Room SID - RM95823ec66a7bbf3e43a7d10df7302df1
   Room State - CONNECTED
   Device - Samsung Galaxy c7 Pro
   
The black screen appears after I get the participant videotrack and until his video appears on the screen. I tried using the onFirstFrameRendered callback but it does not help when I change tracks.

**Comment by aaalaniz** [comment] 2018-01-19 14:52
Hey @shivthepro 

It appears this room resource is no longer available. Can you try to reproduce in another room and send me the SID?

Thanks!

**Comment by shivthepro** [comment] 2018-01-19 15:03
Sure - SID-RM997718b55ba262eb143f448277e2d5bf

Thanks !

**Comment by shivthepro** [comment] 2018-01-23 18:07
Hey @aaalaniz any updates .. are u in need of any information ??

**Comment by aaalaniz** [comment] 2018-01-23 19:38
Hey @shivthepro 

I apologize for the delays. I did not find anything unusual about this Room. I am reaching out to our Media Server infrastructure team to investigate further. I appreciate your patience.

Thanks!

**Comment by aaalaniz** [comment] 2018-02-15 17:23
Closing because workaround provided in #243 resolves this issue.

Thanks @shivthepro !

**Closed by aaalaniz** 2018-02-15 17:23 UTC
Labels: bug
