### ISSUE TITLE
Failed to close camera connection

### ISSUE THREAD

**Issue by rishabhja1994** [twilio/video-quickstart-android#233] opened 2018-01-26 16:52 UTC
### Description

I am facing a crash whenever i try to use camera resource in 2 different places in my app.

### Steps to Reproduce

1. Open second activity with camera from the first camera activity
2.Close the second activity
3. App crashes

#### Code

https://github.com/rishabhja/TwilioTest

#### Expected Behavior

App should not crash

#### Actual Behavior

App crashes

#### Reproduces how Often

100%

#### Logs

01-26 22:16:09.028 22613-22925/? E/Camera-JNI: copyAndPost: off=0, size=460800 msg=10
01-26 22:16:09.055 22613-22807/? W/System.err: java.lang.IllegalStateException: Failed to close camera
01-26 22:16:09.056 22613-22807/? W/System.err:     at com.twilio.video.Preconditions.checkState(Preconditions.java:453)
01-26 22:16:09.056 22613-22807/? W/System.err:     at com.twilio.video.CameraCapturer.stopCapture(CameraCapturer.java:411)
01-26 22:16:09.057 22613-22807/? W/System.err:     at com.twilio.video.VideoCapturerDelegate.stopCapture(VideoCapturerDelegate.java:77)
01-26 22:16:09.057 22613-22807/? E/rtc: #
                                        # Fatal error in /home/travis/build/twilio/twilio-video-android/library/src/main/jni/com_twilio_video_VideoCapturerDelegate.cpp, line 129
                                        # last system error: 0
                                        # Check failed: !jni()->ExceptionCheck()
                                        # error during VideoCapturer.stopCapture
                                        #
01-26 22:16:09.058 22613-22807/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 22807 (Thread-4)
01-26 22:16:09.068 22613-22750/? E/Camera-JNI: copyAndPost: off=0, size=460800 msg=10
### Versions

All relevant version information for issue.

#### Video Android SDK

1.3.9

#### Android API

26

#### Android Device

One plus 5

**Comment by rishabhja1994** [comment] 2018-01-26 17:21
Can someone check this on priority? I have to test it so that i can deploy it in our application

**Comment by aaalaniz** [comment] 2018-01-26 17:22
Hey @rishabhja1994 

Does the problem occur on any other devices?

**Comment by rishabhja1994** [comment] 2018-01-26 17:51
yes

**Comment by rishabhja1994** [comment] 2018-01-26 17:52
You can test by building the project. Just click on Join call and click back button. The app crashes

**Comment by rishabhja1994** [comment] 2018-01-29 06:02
Any progress?

**Comment by aaalaniz** [comment] 2018-01-31 14:55
Hey @rishabhja1994 

I apologize for the delayed response. I've been out sick for a few days. I'll try the test project today.

**Comment by aaalaniz** [comment] 2018-01-31 19:33
Hey @rishabhja1994 

I ran the test project provided and was not able to reproduce the problem on any of my devices. I wonder if this is a problem with just the One Plus 5? What devices are you experiencing the issue on?

Thanks!

**Comment by rishabhja** [comment] 2018-02-05 08:36
The crash can be reproduced everytime. Just press connect button and then press back button instantaneously as the new screen opens. then it would crash.

**Comment by rishabhja** [comment] 2018-02-06 14:41
@aaalaniz What is the difference between onVideoTrackPublished and onVideoTrackSubsribed?

**Comment by aaalaniz** [comment] 2018-02-22 15:44
Hey @rishabhja 

I'm closing this issue as i'm not able to reproduce. I recommend trying to reproduce the scenario in the quickstart.

Thanks!

**Closed by aaalaniz** 2018-02-22 15:44 UTC
Labels: bug
