### ISSUE TITLE
Black screen when renderer remote video track after onVideoTrackSubscribed

### ISSUE THREAD

**Issue by rudyromer** [twilio/video-quickstart-android#536] opened 2020-06-29 23:49 UTC
### Description

Black screen when renderer remote video track after onVideoTrackSubscribed

### Steps to Reproduce

1. Connect to the room
2. Remote participant connect to room without videoTrack published
3. Remote participant publish track after

#### Code

```
override fun onVideoTrackSubscribed(remoteParticipant: RemoteParticipant, remoteVideoTrackPublication: RemoteVideoTrackPublication, remoteVideoTrack: RemoteVideoTrack) {
               addRemoteVideo(remoteVideoTrack)
 }
private fun addRemoteVideo(remoteVideoTrack: RemoteVideoTrack) {
        localVideoTrack.removeRenderer(mainVideoView)
        localVideoTrack.addRenderer(thumbnailVideoView)
        remoteVideoTrack.addRenderer(mainVideoView)
    }

```
#### Expected Behavior

Remote video track show in main video view

#### Actual Behavior

A black screen in main video view

#### Reproduces how Often

100%

### Versions

All relevant version information for issue.

#### Video Android SDK

com.twilio:video-android:5.8.1

#### Android API

29

#### Android Device
One plus 6T (modifié) 

Remote participant is on JavaScipt twilio SDK and local participant on Android

**Comment by Balasnest** [comment] 2020-06-30 13:26
Why this issue suddenly started coming in production? @paynerc I can see a lot of similar issues are raising by others.

**Comment by Balasnest** [comment] 2020-06-30 13:51
Similar issue related to iOS:
[ios - 214](https://github.com/twilio/video-quickstart-ios/issues/214) 
[ios - 240](https://github.com/twilio/video-quickstart-ios/issues/240)

**Comment by rishab1065** [comment] 2020-06-30 14:34
@paynerc I am also facing this issue when call is made from android or ios app to web app

**Comment by paynerc** [comment] 2020-07-13 16:27
@Balasnest 

Both Android and iOS provide callback methods which are called when the first video frame has been rendered.

For Android: `VideoRenderer.Listener.onFirstFrame()`
For iOS: `TVIVideoViewDelegate videoViewDidReceiveData:`

As I mentioned in [iOS 506](https://github.com/twilio/video-quickstart-ios/issues/506), Room Sids would be very useful in diagnosing the delay to first frame. If you can, please provide Room Sids where you are seeing the delay and then we can work through the cause.

Thank you,

Ryan

**Comment by aaalaniz** [comment] 2020-08-19 22:13
Hey @Balasnest 

I am closing this issue for now. Please reopen if you have any further questions or comments.

Thanks!

**Closed by aaalaniz** 2020-08-19 22:13 UTC
Labels: bug

**Comment by tomventura** [comment] 2020-08-20 17:01
Experiencing the same issue. When receiving remote video track subscribe -> unsubscribe -> subscribe within a short time, the last subscribe callback's remoteVideoTrack causes a black screen.

**Comment by rockstardev345** [comment] 2021-02-25 22:44
Any solutions for it ?

**Comment by hktech-group** [comment] 2022-06-10 11:57
Any solutions for it ?
I have the same problem
