### ISSUE TITLE
In Twilio Android SDK Screen comes as black screen for remote participants

### ISSUE THREAD

**Issue by cmargulhano** [twilio/video-quickstart-android#708] opened 2022-03-30 15:04 UTC
### Description

In Twilio Android SDK Screen comes as black screen for remote participants

### Steps to Reproduce

To Reproduce doesn't occur reliably, but mostly happens in the first-time call.

Expected behavior The remote participant screen shouldn't go off as a black screen.

You can find more information in the room where the problem occurred:
![image](https://user-images.githubusercontent.com/11628058/160866741-11394b1f-f627-43c7-87e1-ebd7e92cbfa4.png)

**Comment by afalls-twilio** [comment] 2022-08-24 18:52
@cmargulhano Thank you for the info, sorry about the late response, is this issue still happening with the latest release 7.3.0? (we have since made many changes that may have fix this)

**Comment by afalls-twilio** [comment] 2023-03-16 23:30
Closing due to a lack of customer response

**Closed by afalls-twilio** 2023-03-16 23:30 UTC

**Comment by mithun-bostontech** [comment] 2024-01-17 10:49
I has the same issue with library 7.6.4.
I coudn't able to reproduce again to give additional details but user was having android 13
Please any help, suggestion highly appreciated!!
