### ISSUE TITLE
Video Codec Mismatch In Small Group Room

### ISSUE THREAD

**Issue by PhilipSA** [twilio/video-quickstart-android#401] opened 2019-04-24 11:44 UTC
### Description

Connecting to a small group room with two Android devices supporting different video codecs causes the one that only supports VP8 to get "No supported codec" error when trying to subscribe to the one supporting h.264 video track.

Example room SID: RMaec8210939db07a3610a495820b7887a

We have verified that the group room is correctly setup with VP8 + h.264 codec as described in an other issue: https://github.com/twilio/video-quickstart-android/issues/363

### Steps to Reproduce
1. Connect with computer using latest Google Chrome.
2. Connect with Android device that supports h.264 and have it as preferred codec.
3. Connect with Android device that does not support h.264 and thus does not send in any preferred codecs.

#### Code

```
val isH264Supported = MediaCodecVideoDecoder.isH264HwSupported() && MediaCodecVideoEncoder.isH264HwSupported()
        
// Prefer H264 > VP8
val videoCodecs = mutableListOf<VideoCodec>().apply {
    if (isH264Supported) add(H264Codec())
    add(Vp8Codec())
}

sdkLogger.i("Joining room: $roomName... videoTracks: ${twilioMediaInput.videoTracks} audioTrack: ${twilioMediaInput.audioTracks} videoCodecs: $videoCodecs", TAG)

room = Video.connect(
    context,
    ConnectOptions.Builder(accessToken)
        .roomName(roomName)
        .audioTracks(twilioMediaInput.audioTracks)
        .videoTracks(twilioMediaInput.videoTracks)
        .preferVideoCodecs(videoCodecs)
        .build(),
    this)
```

#### Expected Behavior
Since one of the Android device does not support h.264 it should fallback on VP8

#### Actual Behavior
The device that does not support h.264 get onVideoTrackSubscriptionFailed: "No supported Codec" when trying to subscribe to the Android devices that supports h.264 video.

#### Reproduces how Often
100%

#### Logs
com.twilio.video.TwilioException: No supported codec

### Versions
All

#### Video Android SDK
4.1.1

#### Android API
All

#### Android Device
Devices not supporting h.264

**Comment by aaalaniz** [comment] 2019-04-24 14:58
Hey @PhilipSA 

Thank you for filing this issue. I understand your scenario and what you are experiencing is currently expected behavior with Programmable Video. Our [Managing Codecs Guide](https://www.twilio.com/docs/video/managing-codecs) provides a thorough explanation of the experienced behavior, but I can summarize.

In your scenario, the codec negotiated for the Group room is H.264 because the first two participants connect and support/prefer H.264. As a result, the participants begin sending video using H.264. Later when the Android device which does not support H.264 connects, our media server will attempt to forward H.264 video to the new participant but will fail with a No supported codec exception as you experienced.

There is currently no workaround for this behavior. You could prefer VP8 exclusively in your application, but then Safari users will not be able to subscribe to video. However, [Safari will soon support VP8](https://webkit.org/blog/8672/on-the-road-to-webrtc-1-0-including-vp8/).

I'm happy to answer any follow up questions, but I will close this issue. 

Thanks!

**Closed by aaalaniz** 2019-04-24 14:58 UTC
