### ISSUE TITLE
Complete room api does not disconnect room

### ISSUE THREAD

**Issue by rishabhja** [twilio/video-quickstart-android#277] opened 2018-03-30 09:43 UTC
### Description

Complete room api does not close room for some of the clients. I am not able to receive disconnected event for those clients. This is working for desktop(Js) client.

### Steps to Reproduce

1. Create a call and join multiple people in it.
2. Complete the room.
3. Room does not get disconnected for some of the clients. (randomly)

#### Expected Behavior

Room should disconnect for all the clients.

#### Actual Behavior

Room does not disconnect.

#### Reproduces how Often

100%

#### Android API

21 and above

#### SDK Version

2.0.0 - beta 3

#### Android Device

One Plus 5, Google Pixel, Moto G5

**Comment by rishabhja** [comment] 2018-03-30 13:43
Can someone help me on this? Its blocking for me

**Comment by aaalaniz** [comment] 2018-04-03 14:06
Hey @rishabhja 

Apologies for the delay. I'll look into this today. Just to confirm, you are connecting to a room and then using the [Rooms REST API to complete a room](https://www.twilio.com/docs/video/api/rooms-resource#complete-room)?

Does this problem occur on iOS as well?

Thanks!

**Comment by aaalaniz** [comment] 2018-04-03 16:33
Hey @rishabhja 

I've reproduced the issue and our team is working toward a solution. Did this behavior work in a previous version of the SDK? We don't have test coverage for this scenario, so it's possible we introduced a regression and did not know because of the coverage gap.

Thanks for reporting this issue!

**Comment by aaalaniz** [comment] 2018-04-03 17:03
Another small update. We identified this is only an issue in our 2.x beta releases. I will continue to post updates as we work toward a resolution.

Thanks!

**Comment by aaalaniz** [comment] 2018-04-03 22:08
Hey @rishabhja 

Apologies for the confusion. This issue affects our 2.x preview and beta releases. We have not identified what specific 2.x version introduced this problem. I'll keep you updated. 

Thanks!

**Comment by rishabhja** [comment] 2018-04-10 08:46
Any update on this?

**Comment by aaalaniz** [comment] 2018-04-10 12:12
Hey @rishabhja 

The issue has been resolved in the latest internal release and will be made available in 2.0.0-beta5 soon.

Thanks!

**Comment by aaalaniz** [comment] 2018-04-13 00:29
Hey @rishabhja 

This issue has been fixed in 2.0.0-beta5. Thanks for reporting the issue!

**Closed by aaalaniz** 2018-04-13 00:29 UTC
Labels: bug
