### ISSUE TITLE
SDK cannot be used side-by-side another WebRTC binary

### ISSUE THREAD

**Issue by icochico** [twilio/video-quickstart-android#309] opened 2018-07-09 05:39 UTC
### Description

I have an issue when I try to connect to the room, in particular when I do:

`room = Video.connect(this, connectOptionsBuilder.build(), roomListener());`

Following the example in the quickstart for Java. 
The only difference is that I integrated the code and the dependencies in my app.

#### Logs

```
    java.lang.UnsatisfiedLinkError: No implementation found for void com.twilio.video.Video.nativeSetCoreLogLevel(int) (tried Java_com_twilio_video_Video_nativeSetCoreLogLevel and Java_com_twilio_video_Video_nativeSetCoreLogLevel__I)
        at com.twilio.video.Video.nativeSetCoreLogLevel(Native Method)
        at com.twilio.video.Video.trySetCoreLogLevel(Video.java:284)
        at com.twilio.video.Video.connect(Video.java:108)
        at io.aira.smart.LiveActivity.connectToRoom(LiveActivity.java:381)
```

### Versions

All relevant version information for issue.

#### Video Android SDK

2.1.0

#### Android API

27

#### Android Device

Samsung J7

**Comment by zackm0571** [comment] 2018-07-09 15:00
Hey @icochico, 

Thanks for reaching out. Just wanted to let you know I'm going to be looking into the issue myself. In the interim can you post your call setup code as well as the Twilio dependency in your build.gradle?

**Comment by icochico** [comment] 2018-07-09 18:14
@zackm0571 

Thanks for the help. This is the code that leads to the call:

```
    private void connectToRoom(String roomName) {
        configureAudio(true);
        ConnectOptions.Builder connectOptionsBuilder = new ConnectOptions.Builder(accessToken)
                .roomName(roomName);

        /*
         * Add local audio track to connect options to share with participants.
         */
        if (localAudioTrack != null) {
            connectOptionsBuilder
                    .audioTracks(Collections.singletonList(localAudioTrack));
        }

        /*
         * Add local video track to connect options to share with participants.
         */
        if (localVideoTrack != null) {
            connectOptionsBuilder.videoTracks(Collections.singletonList(localVideoTrack));
        }

        /*
         * Set the preferred audio and video codec for media.
         */
        connectOptionsBuilder.preferAudioCodecs(Collections.singletonList(audioCodec));
        connectOptionsBuilder.preferVideoCodecs(Collections.singletonList(videoCodec));

        /*
         * Set the sender side encoding parameters.
         */
        connectOptionsBuilder.encodingParameters(encodingParameters);

        room = Video.connect(this, connectOptionsBuilder.build(), roomListener());
        //setDisconnectAction();
    }
```
And this is the entire list of my dependencies: 

```
dependencies {
    def androidSupportVersion = '25.2.0'
    def playServiceVersion = '11.0.4'
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    compile "com.android.support:design:$androidSupportVersion"
    compile "com.android.support:appcompat-v7:$androidSupportVersion"
    compile "com.android.support:support-v4:$androidSupportVersion"
    compile "com.android.support:percent:$androidSupportVersion"
    compile "com.google.android.gms:play-services-auth:$playServiceVersion"
    compile "com.google.android.gms:play-services-location:$playServiceVersion"
    compile "com.google.android.gms:play-services:$playServiceVersion"
    compile "com.google.firebase:firebase-core:$playServiceVersion"
    compile "com.google.firebase:firebase-messaging:$playServiceVersion"
    compile "com.google.firebase:firebase-config:$playServiceVersion"
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile 'com.uber.sdk:rides-android:0.5.3'
    compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
    compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
    compile 'com.android.support:multidex:1.0.3'
    compile 'org.jsoup:jsoup:1.10.2'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile "com.mixpanel.android:mixpanel-android:5.4.0"
    compile 'com.lyft:lyft-android-sdk:1.0.3'
    compile 'com.googlecode.libphonenumber:libphonenumber:8.9.1'
    compile 'io.branch.sdk.android:library:2.18.1'
    compile 'com.alimuzaffar.lib:pinentryedittext:1.3.1'
    compile 'com.google.guava:guava:24.1-android'
    //Twilio
    compile "com.twilio:video-android:2.1.0"
    compile "com.koushikdutta.ion:ion:2.1.7"
}
```

**Comment by aaalaniz** [comment] 2018-07-09 18:37
Hey @icochico 

Do you have any native code in your application? The Video Android SDK uses Relinker to load `jingle_peerconnection_so` at runtime. I would expect this error is happening due to a clash in native libraries.

Thanks!

**Comment by icochico** [comment] 2018-07-09 18:43
@aaalaniz great guess, yes I do have native code in my app.

In particular, I am using exactly this:

`libjingle_peerconnection_so.so`

**Comment by aaalaniz** [comment] 2018-07-09 19:08
Hey @icochico 

Unfortunately, this is a known issue with our Video Android SDK. We do not currently support side-by-side usage of other WebRTC based SDKs or WebRTC binaries. This requires some significant changes to the way we build and integrate WebRTC. We are prioritizing the work to make this possible, but I cannot provide a timeline at this time.

I'll update the title of the ticket and provide any updates on this bug as we make progress.

Thanks!

**Comment by icochico** [comment] 2018-07-09 19:29
@aaalaniz thanks for your quick answer.

As soon as you posted about `jingle_peerconnection_so` I understood the issue. Unfortunately we also made changes to the library to support some of our API actions to happen during a WebRTC streaming, so we have our own implementation of it. One solution for us would be to apply our changes on top of yours, is the license of your WebRTC implementation compatible with this? If that's the case, could you give me a link to your source?

**Comment by aaalaniz** [comment] 2018-07-10 16:29
Hey @icochico 

Unfortunately we do not allow contributions to our SDK or WebRTC source. I recommend reaching out to @ktoraskartwilio to discuss using Twilio Video to accommodate your needs.

Thanks!

**Comment by aaalaniz** [comment] 2019-01-18 17:54
Duplicate of #340

**Closed by aaalaniz** 2019-01-18 17:54 UTC
Labels: bug
