### ISSUE TITLE
Crash when switching cameras on Samsung "plus" phones (Tab, S20)

### ISSUE THREAD

**Issue by mcorner** [twilio/video-quickstart-android#493] opened 2020-04-07 15:32 UTC
### Description

Customers are getting crashes on particular Samsung models:

SM-G988U
SM-N975U
SM-G986U
SM-N976V

We have bugsnag reports and one customer reported that it crashed every time he switched cameras (from the front camera to the back).

Possibly related to #419 or #431 

### Steps to Reproduce

We don't have one of these devices ATM, but customer reported that switching cameras immediately crashed the app.

#### Code

We can provide more code, but our cameracompat code is probably the most relevant:
https://gist.github.com/mcorner/2670dc6a7ef8957e2a0557600005f4fb

#### Expected Behavior

Not crash

#### Actual Behavior

Crash with NPE

#### Reproduces how Often

We don't know exactly, but customer reported 100%.

#### Logs

```
java.lang.NullPointerException · Attempt to get length of null array
Camera2Enumerator.java:231org.webrtc.Camera2Enumerator.convertSizes	
Camera2Enumerator.java:146org.webrtc.Camera2Enumerator.getSupportedSizes	
Camera2Session.java:355org.webrtc.Camera2Session.findCaptureFormat	
Camera2Session.java:343org.webrtc.Camera2Session.start	
Camera2Session.java:326org.webrtc.Camera2Session.<init>	
Camera2Session.java:302org.webrtc.Camera2Session.create	
Camera2Capturer.java:36org.webrtc.Camera2Capturer.createCameraSession	
CameraCapturer.java:306org.webrtc.CameraCapturer$5.run	
Handler.java:883android.os.Handler.handleCallback	
Handler.java:100android.os.Handler.dispatchMessage	
Looper.java:237android.os.Looper.loop	
HandlerThread.java:67android.os.HandlerThread.run
```

### Versions

Android 10

#### Video Android SDK

    implementation 'com.twilio:video-android:5.0.0-beta2'

#### Android API

    compileSdkVersion 28
    buildToolsVersion "28.0.3"
        minSdkVersion 21
        targetSdkVersion 28

#### Android Device

See description.

**Comment by aaalaniz** [comment] 2020-04-07 16:03
Hey @mcorner 

I think the tickets #419 and #431 are relevant, but this may be a new issue with a camera ID that does not behave properly when used to capture video for the purposes of streaming. Thank you for the CameraCapturerCompat reference. I did notice that your CameraCapturerCompat does not contain the latest code that works around a couple of known issues with certain cameras. Please update your CameraCapturerCompat the latest [code](https://github.com/twilio/video-quickstart-android/blob/master/quickstart/src/main/java/com/twilio/video/quickstart/util/CameraCapturerCompat.java).

We are currently considering incorporating CameraCapturerCompat into the SDK itself so that we can improve the quality and ship out updates for these types of issues ourselves.

Thanks!

**Comment by mcorner** [comment] 2020-04-14 11:40
Ok, thank you @aaalaniz. We are deploying the new CameraCapturerCompat code.  Having that in the SDK instead would be a win.  

If that doesn't work then we are going to have to deploy model specific code to disable our flip camera button.  That is bad for our product in general, but will also be whack-a-mole since Samsung is continuously producing new models.

Let me know when you have a confirmed fix, thanks.

On a side note: do you know of a good way to test on new Samsung devices (other than buying all of them?).  AWS Device farm doesn't seem to have them and the emulator is generally insufficient for camera/audio/hw stuff.

**Comment by aaalaniz** [comment] 2020-04-15 15:51
Hey @mcorner 

>We are deploying the new CameraCapturerCompat code. Having that in the SDK instead would be a win

I've cut a ticket for integrating the CameraCapturerCompat into our SDK. I think it would be helpful to have this capturer in the SDK with a mechanism to filter camera IDs that are either not meant for sharing real-time video (infrared camera) or contain known issues (unsupported capturing format).

>If that doesn't work then we are going to have to deploy model specific code to disable our flip camera button. That is bad for our product in general, but will also be whack-a-mole since Samsung is continuously producing new models.

>Let me know when you have a confirmed fix, thanks.

We will do our best to ensure that your team does not have to employ disabling camera switching 😄 We don't have a confirmed fix right now because we have not reproduced. We run a number of capturing tests on [Firebase Test Lab (FTL)](https://firebase.google.com/docs/test-lab) and this issue has not emerged in recent runs. I will close this issue for now as it's not actionable at the moment. However, if you continue to observe crashes in the field, please let us know and we will order a device and get the issue triaged and fixed ASAP.

>On a side note: do you know of a good way to test on new Samsung devices (other than buying all of them?). AWS Device farm doesn't seem to have them and the emulator is generally insufficient for camera/audio/hw stuff.

As I stated before, we use FTL for our device testing. They have a number of Samsung devices for testing. (Quick output below)

| MODEL_ID | MAKE | MODEL_NAME | FORM | RESOLUTION | OS_VERSION_IDS |
| --- | --- | --- | --- | --- | --- |
| Nexus10           | Samsung            | Nexus 10                             | VIRTUAL  | 2560 x 1600 | 19,21,22             |
| SC-03K            | Samsung            | Samsung S9+, SC-03K                  | PHYSICAL | 2960 x 1440 | 28                   |
| a5y17lte          | Samsung            | Galaxy A5 2017                       | PHYSICAL | 1920 x 1080 | 24                   |
| a9y18qlte         | Samsung            | A9 2018                              | PHYSICAL | 2220 x 1080 | 26                   |
| a9y18qltechn      | Samsung            | Samsung SM-A9200                     | PHYSICAL | 2220 x 1080 | 26                   |
| astarqltechn      | Samsung            | Galaxy A8 Star                       | PHYSICAL | 2220 x 1080 | 26                   |
| astarqlteskt      | Samsung            | Samsung A8 Star                      | PHYSICAL | 2220 x 1080 | 26                   |
| beyond1           | Samsung            | Galaxy S10 SM-G973F                  | PHYSICAL | 3040 x 1440 | 28                   |
| c5proltechn       | Samsung            | Samsung C5 Pro                       | PHYSICAL | 1920 x 1080 | 26                   |
| crownlte          | Samsung            | Samsung Note 9                       | PHYSICAL | 2960 x 1440 | 28                   |
| crownlteks        | Samsung            | Samsung Note 9 SM-N960N              | PHYSICAL | 2960 x 1440 | 28                   |
| crownqlteue       | Samsung            | Galaxy Note 9 USA                    | PHYSICAL | 2960 x 1440 | 27                   |
| cruiserlteatt     | Samsung            | Samsung Galaxy S8 Active             | PHYSICAL | 2220 x 1080 | 26                   |
| cruiserltesq      | Samsung            | Samsung S8 Active                    | PHYSICAL | 2220 x 1080 | 26                   |
| dream2lte         | Samsung            | Samsung S8+ SM-G955F                 | PHYSICAL | 2960 x 1440 | 26                   |
| dream2lteks       | Samsung            | Galaxy S8+ SM-G955N                  | PHYSICAL | 2960 x 1440 | 26                   |
| dream2qlteue      | Samsung            | Samsung S8+ SM-G955U1                | PHYSICAL | 2220 x 1080 | 26                   |
| dreamqlteue       | Samsung            | Galaxy S8                            | PHYSICAL | 2960 x 1440 | 26                   |
| grandpplte        | Samsung            | Galaxy J2 Prime SM-G532M             | PHYSICAL |  960 x 540  | 23                   |
| greatlte          | Samsung            | Samsung Galaxy Note 8 (SM-N950F)     | PHYSICAL | 2960 x 1440 | 28                   |
| greatqlte         | Samsung            | Samsung Note 8                       | PHYSICAL | 2220 x 1080 | 26                   |
| gts3lltevzw       | Samsung            | Samsung Tab S3 Verizon SM-T827V      | PHYSICAL | 2048 x 1536 | 28                   |
| gts4lltevzw       | Samsung            | Samsung SM-T837V                     | PHYSICAL | 2560 x 1600 | 28                   |
| hero2lte          | Samsung            | Galaxy S7 edge                       | PHYSICAL | 1440 x 2560 | 23                   |
| hero2qlteatt      | Samsung            | Samsung Galaxy S7 edge ATT           | PHYSICAL | 2560 x 1440 | 26                   |
| hero2qltechn      | Samsung            | Galaxy S7 SM-G9350                   | PHYSICAL | 2560 x 1440 | 26                   |
| hero2qltespr      | Samsung            | Samsung S7 Edge Sprint               | PHYSICAL | 2560 x 1440 | 26                   |
| hero2qltetmo      | Samsung            | Samsung Galaxy S7 edge T-Mobile      | PHYSICAL | 2560 x 1440 | 26                   |
| hero2qlteusc      | Samsung            | Galaxy S7 Edge SM-G935R4             | PHYSICAL | 2560 x 1440 | 26                   |
| hero2qltevzw      | Samsung            | Samsung Galaxy S7 edge Verizon G935V | PHYSICAL | 2560 x 1440 | 26                   |
| heroqlteaio       | Samsung            | Samsung S7 SM-G930AZ for Cricket     | PHYSICAL | 2560 x 1440 | 26                   |
| heroqlteatt       | Samsung            | Samsung S7 ATT                       | PHYSICAL | 1920 x 1080 | 26                   |
| heroqltespr       | Samsung            | Samsung S7 Sprint                    | PHYSICAL | 2560 x 1440 | 26                   |
| heroqltetfnvzw    | Samsung            | Galaxy S7 (Straight Talk) SM-G930VL  | PHYSICAL | 2560 x 1440 | 26                   |
| heroqltetmo       | Samsung            | Samsung S7 SM-G930T T-Mobile         | PHYSICAL | 2560 x 1440 | 26                   |
| heroqltevzw       | Samsung            | Samsung S7 Verizon                   | PHYSICAL | 2560 x 1440 | 26                   |
| hlte              | Samsung            | Galaxy Note 3 Duos                   | PHYSICAL | 1920 x 1080 | 19                   |
| j1acevelte        | Samsung            | Galaxy J1 ace SM-J111M               | PHYSICAL |  800 x 480  | 22                   |
| j7xelte           | Samsung            | Galaxy J7 (SM-J710MN)                | PHYSICAL | 1280 x 720  | 23                   |
| lt02wifi          | Samsung            | Galaxy Tab 3                         | PHYSICAL |  600 x 1024 | 19                   |
| m0                | Samsung            | Samsung Galaxy S3                    | PHYSICAL | 1280 x 720  | 18                   |
| poseidonlteatt    | Samsung            | Samsung S7 Active ATT                | PHYSICAL | 1920 x 1080 | 26                   |
| star2lte          | Samsung            | Samsung S9+ SM-G965F                 | PHYSICAL | 2960 x 1440 | 28                   |
| star2lteks        | Samsung            | Samsung S9+ SM-G965N                 | PHYSICAL | 2220 x 1080 | 28                   |
| star2qlteue       | Samsung            | Samsung Galaxy S9+ (US)              | PHYSICAL | 2220 x 1080 | 26                   |
| starlte           | Samsung            | Samsung Galaxy S9 SM-G960F           | PHYSICAL | 2960 x 1440 | 26                   |
| starlteks         | Samsung            | Galaxy S9 (Korea)                    | PHYSICAL | 2220 x 1080 | 28                   |
| starqltechn       | Samsung            | Samsung Galaxy S9 SM-G9600           | PHYSICAL | 2960 x 1440 | 26                   |
| starqlteue        | Samsung            | Samsung Galaxy S9 (US)               | PHYSICAL | 2220 x 1080 | 26                   |
| zeroflte          | Samsung            | Galaxy S6                            | PHYSICAL | 2560 x 1440 | 23                   |

**Closed by aaalaniz** 2020-04-15 15:51 UTC
Labels: bug

**Comment by mcorner** [comment] 2020-04-22 20:38
Excellent, thanks for the help. We haven’t seen the same crash after implementing the cameracompat changes, so we believe this fixed it. I will report back if not, but the probability is high that it is fixed.

**Comment by sunit-navsoft** [comment] 2020-06-18 09:52
Getting crash report while using camera for LGE Nexus 5X with Android OS version 8.1.0

My Crash log says:
: java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.util.Pair.first' on a null object reference
