### ISSUE TITLE
Help understanding participant listener methods

### ISSUE THREAD

**Issue by rishabhja** [twilio/video-quickstart-android#236] opened 2018-02-06 14:46 UTC
Can you add documentation or explain the methods in RemoteParticipant.Listener

**Comment by aaalaniz** [comment] 2018-02-06 14:59
Hey @rishabhja 

I recommend [reading the answer I provided on another issue](https://github.com/twilio/video-quickstart-android/issues/183#issuecomment-339120770). In addition, I recommend reading our [migration guide](https://www.twilio.com/docs/api/video/migrating-1x-2x-android-20). Even if you are not migrating from 1.x to 2.x the guide is still useful for understanding the 2.x API.

Thanks!

**Comment by rishabhja** [comment] 2018-02-12 14:13
@aaalaniz I could not find it anywhere about on which thread are the callback methods executed (Ui, or some other thread)? Should I assume that they are executed asynchronously as well?

**Comment by aaalaniz** [comment] 2018-02-12 14:58
Hey @rishabhja 

RemoteParticipant callbacks are asynchronous and invoked on the same thread that called `Video.connect`. I do not see this contract documented anywhere in our API docs or guides. I will create a task for this so other developers do not encounter the same confusion.

Thanks!

**Comment by rishabhja** [comment] 2018-02-13 14:25
Thanks for the quick reply. One query that i also faced was that if the callback methods are guranteed to be executed in order. For example, is it possible that i receive a disconnect event of a participant later than his reconnection(his second onConnected event) event.

**Comment by aaalaniz** [comment] 2018-02-13 15:12
Hey @rishabhja 

The callback methods should be executed in order. In the scenario you describe the expected sequence of callback events should be:

Initial participant connected callback
`onParticipantConnected` 

Participant disconnected
`onParticipantDisconnected`

Participant reconnected
`onParticipantConnected`

If you are receiving these callbacks in a different order for the scenario described please open a separate issue with steps to reproduce and I will triage ASAP. 

Thanks!

**Comment by rishabhja** [comment] 2018-02-13 18:47
Thanks for the information. I just wanted to confirm if that could happen. 

How is it conveyed via sdk if a user has turned off his video?

**Comment by rishabhja** [comment] 2018-02-14 19:12
Okay.

VideoView.Listener gives me a firstFrame callback. Is it for the first frame that gets rendered onto it?

**Comment by aaalaniz** [comment] 2018-02-14 19:34
Hey @rishabhja 

Yes this callback is invoked when VideoView renders the first frame. Can you post a crash log?

Thanks!

**Comment by rishabhja** [comment] 2018-02-14 19:42
The crash was due to the fact that the callback was not executed on UI thread. But I am not getting callback for the first frame rendered sometimes. My use case is that till the time the first frame in not rendered, i need to show a placeholder instead of empty videoview. So, i have attached the listener as soon as i create the view. But it does not get called.

`package to.go.ui.utils.views;

import android.content.Context;
import android.databinding.BindingAdapter;
import android.util.AttributeSet;
import android.view.LayoutInflater;
import android.widget.LinearLayout;

import com.twilio.video.LocalVideoTrack;
import com.twilio.video.VideoRenderer.Listener;
import com.twilio.video.VideoTrack;
import com.twilio.video.VideoView;

import to.go.R;
import to.go.ui.contacts.AvatarView;
import to.talk.logging.Logger;
import to.talk.logging.LoggerFactory;
import to.talk.ui.utils.async.UICaller;

public class CustomVideoView extends LinearLayout
{
    protected VideoView _videoView;
    protected AvatarView _avatarView;
    private VideoTrack _currentVideoTrack;
    private static final Logger _logger = LoggerFactory
        .getTrimmer(CustomVideoView.class, "custom-video-view");

    public CustomVideoView(Context context)
    {
        super(context);
        initViews();
    }

    public CustomVideoView(Context context, AttributeSet attrs)
    {
        super(context, attrs);
        initViews();
    }

    public void setAvatar(String avatarUrl)
    {
        _avatarView.setAvatarUrl(avatarUrl);
    }

    public VideoView getVideoView()
    {
        return _videoView;
    }

    public AvatarView getAvatarView()
    {
        return _avatarView;
    }

    public VideoTrack getCurrentVideoTrack()
    {
        return _currentVideoTrack;
    }

    public void setCurrentVideoTrack(VideoTrack videoTrack)
    {
        _currentVideoTrack = videoTrack;
    }

    protected void initViews()
    {
        LayoutInflater inflater = (LayoutInflater) getContext()
            .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        inflater.inflate(R.layout.custom_video_view, this, true);
        _videoView = findViewById(R.id.video_view);
        _videoView.applyZOrder(true);
        _videoView.setListener(new Listener()
        {
            @Override
            public void onFirstFrame()
            {
                UICaller.runOnUI(() -> {
                    _avatarView.setVisibility(GONE);
                    _videoView.setVisibility(VISIBLE);
                }, _logger);
            }

            @Override
            public void onFrameDimensionsChanged(int i, int i1, int i2)
            {

            }
        });
        _avatarView = findViewById(R.id.avatar_view);
        _avatarView.setAvatarUrl(null);
    }

    @BindingAdapter("app:stream")
    public static void addStream(CustomVideoView videoView, VideoTrack videoTrack)
    {
        if (videoView.getCurrentVideoTrack() != null) {
            if (videoView.getCurrentVideoTrack() instanceof LocalVideoTrack) {
                LocalVideoTrack localVideoTrack = (LocalVideoTrack) videoView
                    .getCurrentVideoTrack();
                try {
                    localVideoTrack.removeRenderer(videoView.getVideoView());
                } catch (IllegalStateException e) {
                    _logger
                        .debug("Error occurred while removing previous stream from view : {}", e);
                }
            } else {
                videoView.getCurrentVideoTrack().removeRenderer(videoView.getVideoView());
            }
        }
        videoView.setCurrentVideoTrack(videoTrack);
        if (videoTrack == null) {
            videoView.getAvatarView().setVisibility(VISIBLE);
            videoView.getVideoView().setVisibility(GONE);
        } else {
            videoTrack.addRenderer(videoView.getVideoView());
        }
    }

    @BindingAdapter("app:overlaySurface")
    public static void setOverlaySurface(CustomVideoView videoView, boolean overlaySurface)
    {
        videoView.getVideoView().setZOrderMediaOverlay(overlaySurface);
    }
}
`

**Comment by aaalaniz** [comment] 2018-02-14 19:49
Hey @rishabhja 

I can't tell from the snippet but is it possible that the VideoView is added to the video track as a renderer before the VideoView listener is set?

**Comment by rishabhja** [comment] 2018-02-14 19:54
I checked that case. The issue is that, assume a VideoView was streaming a track. If i remove that track and start another, then firstFrameRendered is not called

**Comment by aaalaniz** [comment] 2018-02-14 20:03
Ah I see! Good catch.

Currently this is the expected behavior, but I definitely see the value in surfacing the first frame rendered for each video track instead of just the first frame the VideoView renders. I'll had a task to our backlog to explore supporting this. 

I can think of two workarounds for this issue.

1. Use a unique VideoView for each VideoTrack. This ensures that first frame callback is invoked every time.
2. Try updating your UI when you receive the `onVideoTrackSubscribed` event. Video should be visible shortly after this event. I don't think this works better than option 1, but it's worth a try.

Thanks for helping diagnose this issue!

**Comment by rishabhja** [comment] 2018-02-14 20:09
I can't do that because that would use a lot of memory. Also, the time that a video starts is pretty large sometimes.. so I would need some other way out for this

**Comment by aaalaniz** [comment] 2018-02-14 20:17
Hey @rishabhja 

I'm closing this issue because I think the original questions have been answered. I'll open up a new issue capturing this request and prioritize the work ASAP.

Thanks

**Closed by aaalaniz** 2018-02-14 20:17 UTC
Labels: question
